// ═══════════════════════════════════════════════════════════════════
// Nodo · shalom-agencias.ts — destinos de Shalom tomados de la columna DESTINO
// de su Excel de carga masiva. ESPEJO de panel/courier/listas.json →
// shalom.destino. Si Shalom cambia su plantilla, REGENERAR AMBOS (mismo origen).
//
// ⚠️ NO es el directorio completo de Shalom ni se actualiza solo: mientras no
// exista su API, esta lista es lo único que hay, y es PARCIAL. Se usa en una
// sola dirección — sirve para CONFIRMAR (si el cliente nombra una oficina que
// está acá, el destino es seguro), nunca para DESCARTAR ni para deducir cuántas
// oficinas tiene una ciudad. Todo lo que no calce se marca para que un humano lo
// coordine con el cliente en Pedidos; la venta nunca se bloquea por esto.
// ═══════════════════════════════════════════════════════════════════

export const AGENCIAS_SHALOM: string[] = [
  "AAHH SANTA ROSA PIURA",
  "ABANCAY",
  "AGUAS VERDES",
  "AGUAYTÍA",
  "ALTO PUNO",
  "ALTO TRUJILLO",
  "AMARILIS CO",
  "AMBO",
  "ANCON",
  "ANDAHUAYLAS",
  "AÑO NUEVO",
  "ANT PANAM SUR CDRA 11",
  "ANTA IZCUCHACA",
  "APLAO",
  "ASOC LAS FLORES -  AV 54",
  "ASOC. NUEVO HORIZONTE - AV. 54",
  "ATAHUALPA",
  "ATOCONGO",
  "AUCAYACU",
  "AUTOPISTA LA JOYA",
  "AV  4 DE NOVIEMBRE CO",
  "AV  BALTA CDRA. 36",
  "AV  BOLIVAR",
  "AV  CENTRAL  SMP",
  "AV  ESPERANZA",
  "AV  FLORA TRISTAN",
  "AV  INDEPENDENCIA",
  "AV  JOSE GALVEZ",
  "AV  LA FONTANA",
  "AV  MARCO PUENTE",
  "AV  NICOLAS DUEÑAS CDRA. 5",
  "AV  QUILCA",
  "AV  SAN JUAN PAMPLONA ALTA",
  "AV  SANTA ROSA - STA ANITA",
  "AV  TUPAC AMARU KM. 19",
  "AV  VIGIL",
  "AV 15 DE AGOSTO",
  "AV ABRAHAM VALDELOMAR CO",
  "AV ALAMEDA DEL CORREGIDOR",
  "AV ANTONIO LORENA",
  "AV AUGUSTO SALAZAR BONDY",
  "AV BERTELLO CALLAO",
  "AV BERTELLO SMP",
  "AV BUENOS AIRES",
  "AV CENTRAL SJL",
  "AV CHARCANI",
  "AV CIRCUNVALACIÓN CRUCE CON MARIATEGUI",
  "AV CIRCUNVALACION NAZCA",
  "AV CIRCUNVALACION SJL",
  "AV COLONIZADORES  CO",
  "AV COSTANERA",
  "AV EJERCITO",
  "AV EL SOL",
  "AV ENRIQUE MEIGGS",
  "AV FERNANDO BELAUNDE",
  "AV HERMANOS ANGULO",
  "AV HEROES DEL PACIFICO CO",
  "AV HNOS UCEDA - AMERICA NORTE",
  "AV HUANDOY CON AV CENTRAL",
  "AV HUANDOY CON MARAÑON",
  "AV JESUS",
  "AV JOSE A. QUIÑONES",
  "AV JOSE GRANDA CDRA 38",
  "AV JOSE GRANDA CDRA. 25",
  "AV JOSE LEAL CDRA 6",
  "AV JOSE SACO ROJAS",
  "AV LAS AMERICAS",
  "AV LIMA",
  "AV LOS INCAS",
  "AV MALECON  CHECA CDRA. 1",
  "AV MANUEL VALLE",
  "AV MARISCAL CASTILLA CO PARQUE INDUSTRIAL",
  "AV MEXICO CO",
  "AV MIGUEL GRAU  PAMPLONA ALTA",
  "AV PACHACUTEC",
  "AV PARRA 379 CO",
  "AV PARTICIPACION PARCELA",
  "AV PUMACAHUA",
  "AV RAUL MATA LA CRUZ- DOS GRIFOS",
  "AV SAENZ PEÑA",
  "AV SANTA ROSA URB LOS ALAMOS",
  "AV SOCABAYA - LOS TORITOS",
  "AV TACNA",
  "AV TAHUANTINSUYO",
  "AV TOMAS MARSANO - LA BOLICHERA",
  "AV TUPAC AMARU CDRA. 57",
  "AV UNIV.  RETABLO",
  "AV VENEZUELA",
  "AV VICTOR R. HAYA CO",
  "AV. 13 DE ENERO",
  "AV. ANGAMOS",
  "AV. ANGELICA GAMARRA",
  "AV. ARIAS ARAGUEZ",
  "AV. CANADA",
  "AV. CANEVARO",
  "AV. CANTA CALLAO  CON ALISOS",
  "AV. CANTA CALLAO CON IZAGUIRRE",
  "AV. CARLOS IZAGUIRRE CDRA. 14",
  "AV. CARLOS IZAGUIRRE CUADRA 23",
  "AV. CESAR VALLEJO",
  "AV. DEL MERCADO",
  "AV. DOMINICOS CDRA 14",
  "AV. DOS DE OCTUBRE",
  "AV. GERARDO UNGER CDRA 64",
  "AV. GRAU",
  "AV. GULLMAN",
  "AV. HORACIO ZEVALLOS",
  "AV. HUANCANE CDRA. 9",
  "AV. HUAROCHIRÍ",
  "AV. LA MARINA",
  "AV. LA MOLINA CDRA. 35",
  "AV. LAMPA",
  "AV. LAS MAGNOLIAS",
  "AV. LAS PALMERAS",
  "AV. LIMA - VMT",
  "AV. LIMA CDRA 38",
  "AV. LOS PESCADORES CO",
  "AV. LOS PLATINOS",
  "AV. LUIS EGUIGUREN",
  "AV. MODESTO BORDA",
  "AV. MUNICIPAL",
  "AV. PACÍFICO BELEN",
  "AV. PASTOR SEVILLA",
  "AV. PERU 15",
  "AV. PRINCIPAL",
  "AV. SAN LORENZO",
  "AV. SANTA ROSA CRUCE AV. EL SOL",
  "AV. TRAPICHE",
  "AV. TUPAC AMARU KM. 23.5",
  "AV. UNIV. PARQUE SINCHI ROCA",
  "AV. UNIVERSITARIA CDRA. 16",
  "AV. VILLA MARIA",
  "AVIACION 2819",
  "AYABACA",
  "AYACUCHO CO",
  "AYAVIRI",
  "AZANGARO",
  "BAGUA CAPITAL",
  "BAGUA GRANDE",
  "BAMBAMARCA",
  "BAÑOS DEL INCA",
  "BARRANCA",
  "BARRIO SAN JOSE",
  "BARRIO SAN MARTÍN",
  "BAYOVAR",
  "BELLAVISTA CALLAO",
  "BELLAVISTA SULLANA",
  "CACHIMAYO - SAN SEBASTIAN",
  "CAJABAMBA",
  "CAJAMARCA CO",
  "CAJAMARCA HORACIO ZEVALLOS",
  "CALLAO FAUCETT",
  "CALLE A  CON AV INDUSTRIAL",
  "CALLE EMAÚS",
  "CALLE LIMA",
  "CALLE LIVERPOOL",
  "CALLE LOS ANGELES",
  "CALLE SANTA CRUZ - AMERICA SUR",
  "CALLE TAHUANTINSUYO",
  "CALLE YARABAMBA",
  "CALLERIA AV SAENZ PEÑA",
  "CALLERIA JR JOSE GALVEZ",
  "CAMANA",
  "CAMPOY",
  "CAÑETE IMPERIAL",
  "CAÑETE SAN VICENTE",
  "CANTO GRANDE",
  "CARABAYLLO ESTABLO",
  "CARAZ",
  "CARHUAZ",
  "CARMEN ALTO",
  "CASA GRANDE",
  "CASMA",
  "CATACAOS",
  "CELENDIN",
  "CERCADO MOLLENDO",
  "CERRO DE PASCO",
  "CHACHAPOYAS CO DOS DE MAYO",
  "CHACHAPOYAS JR GRAU",
  "CHALA",
  "CHALLHUAHUACHO",
  "CHANCAY",
  "CHAO",
  "CHEN CHEN",
  "CHEPEN",
  "CHILCA HUANCAYO",
  "CHILCA LEONCIO PRADO",
  "CHILETE - AGENTE",
  "CHINCHA PUEBLO NUEVO",
  "CHINCHERO",
  "CHONGOYAPE",
  "CHORRILLOS CO",
  "CHORRILLOS LOS FAISANES",
  "CHOSICA",
  "CHOTA",
  "CHULUCANAS",
  "CHUPACA",
  "CIENEGUILLA KM. 14.5",
  "CIUDAD DE DIOS",
  "CIUDAD MUNICIPAL",
  "CIUDAD UNIVERSITARIA",
  "COCACHACRA",
  "COMBAPATA",
  "CONCEPCION",
  "CORRALES",
  "CRUZ DE MOTUPE",
  "CTRA IQUITOS NAUTA",
  "CUSCO CALCA",
  "CUSCO CO VIA EVITAMIENTO",
  "CUSCO PARQUE INDUSTRIAL",
  "CUSCO URUBAMBA",
  "CUTERVO",
  "DESAGUADERO",
  "EL ALTO",
  "EL CRUCE LA JOYA",
  "EL MILAGRO",
  "EL PROGRESO KM 22",
  "EL TRIUNFO",
  "ESPINAR",
  "FERREÑAFE",
  "FIORI",
  "GARATEA",
  "GERMÁN AGUIRRE",
  "GUADALUPE LA LIBERTAD",
  "HIGUERETA",
  "HUACHO AV  INDACOCHEA",
  "HUAMACHUCO",
  "HUAMBOCANCHA BAJA",
  "HUANCABAMBA",
  "HUANCARO",
  "HUANCAVELICA",
  "HUANCAYO JR. ICA",
  "HUANTA",
  "HUARACLLA",
  "HUARAL",
  "HUARAZ",
  "HUARMEY",
  "HUAURA",
  "HUAYCAN  EL DESCANSO",
  "HUAYCAN AV HORACIO ZEVALLOS",
  "HUAYCAN AV JOSE C MARIATEGUI",
  "HUAYCAN ENTRADA",
  "HUAYLLAY",
  "IBERIA",
  "ICA AV. JJ ELIAS",
  "ICA SAN JOAQUIN",
  "ICA SANTIAGO",
  "ICA SUBTANJALLA CO",
  "ICA URB. MANZANILLA",
  "IGNACIO ESCUDERO",
  "ILAVE",
  "ILO CO PAMPA INALAMBRICA",
  "ILO PACOCHA",
  "ILO PUERTO",
  "IQUITOS  AV TUPAC AMARU",
  "IQUITOS CO JR. PABLO ROSSELL",
  "IQUITOS JR FRANCISCO BOLOGNESI",
  "JACOBO HUNTER",
  "JAEN",
  "JAUJA",
  "JAYANCA",
  "JESUS MARIA",
  "JESUS NAZARENO",
  "JICAMARCA",
  "JIRON ANCASH",
  "JR  FREDY ALIAGA CO",
  "JR AGUILAR",
  "JR AGUSTIN GAMARRA",
  "JR CASANOVA CON PETIT THOUARS",
  "JR CESAR VALLEJO",
  "JR CHINCHAYSUYO CDRA 4",
  "JR LEONCIO PRADO",
  "JR. CAHUIDE",
  "JR. HUARAZ -  BREÑA",
  "JR. MAMA OCLLO",
  "JR. RAMÓN CASTILLA",
  "JR. RAYMONDI",
  "JR. TAHUANTINSUYO",
  "JUANJUI  CENTRO",
  "JUANJUÍ FERNANDO BELAUNDE TERRY CO",
  "LA CINCUENTA",
  "LA CRUZ  TUMBES",
  "LA CURVA DE MANCHAY",
  "LA MERCED",
  "LA OROYA",
  "LA TINGUIÑA",
  "LA UNION",
  "LA VILLA  CRUCE PISCO",
  "LAMAS",
  "LAMBAYEQUE CENTRO",
  "LAMBAYEQUE PANAMERICANA",
  "LARCOMAR",
  "LAS CONCHITAS",
  "LAS DELICIAS DE VILLA",
  "LAS LOMAS",
  "LAS MERCEDES",
  "LIMA AV TINGO MARÍA",
  "LOS FRESNOS",
  "LOS ORGANOS",
  "LOS PINOS",
  "LOS SAUCES",
  "LUYA",
  "MAGDALENA DEL MAR",
  "MALA",
  "MALL LAMBRAMANI",
  "MALVINAS - JR. GARCIA VILLóN",
  "MALVINAS - JR. RICARDO TRENEMAN",
  "MANANTAY  AV AGUAYTIA",
  "MANANTAY AV TUPAC AMARU",
  "MANCHAY TRES MARIAS",
  "MÁNCORA",
  "MARIA AUXILIADORA",
  "MARIANO MELGAR",
  "MARISCAL NIETO",
  "MATARANI",
  "MAZAMARI",
  "MAZUKO",
  "MEGAPLAZA CHORRILLOS",
  "MEGAPLAZA INDEPENDENCIA",
  "MI PERU",
  "MIRAFLORES AREQUIPA",
  "MIRAFLORES CHICLAYO",
  "MOCHE",
  "MOLLENDO CO",
  "MONSEFU",
  "MORROPE",
  "MORROPON",
  "MOTUPE",
  "MOYOBAMBA  CENTRO",
  "NUEVA CAJAMARCA",
  "NUEVA ESPERANZA VMT",
  "NUEVO IMPERIAL CO",
  "NUEVO LURIN",
  "OCONGATE",
  "OLMOS",
  "OROPESA",
  "OTUZCO",
  "OVALO DE LA FAMILIA",
  "OVALO HUANCHACO CO",
  "OVALO LA PERLA",
  "ÓVALO MARIÁTEGUI",
  "OVALO ORQUIDEAS CO",
  "OVALO PAPAL",
  "OVALO PUENTE PIEDRA",
  "OXAPAMPA",
  "PACANGUILLA",
  "PACASMAYO CENTRO",
  "PACASMAYO LAS PALMERAS",
  "PACHACUTEC  AV 150",
  "PACHACUTEC PDRO CHINITAS",
  "PACHACUTEC PDRO VC",
  "PAIJAN",
  "PAIMAS",
  "PAITA",
  "PAMPA GRANDE TUMBES",
  "PANGOA",
  "PARAD.  LOS LICENCIADOS",
  "PARAMONGA",
  "PARCONA",
  "PARDO MIGUEL NARANJOS",
  "PARQUE INDUSTRIAL CO PIURA FUTURA",
  "PARQUE LA MOLINA",
  "PATAPO",
  "PEDRO RUIZ",
  "PERENE",
  "PESQUERO",
  "PICHANAKI",
  "PICOTA",
  "PILCOMAYO",
  "PIMENTEL",
  "PIO  PATA",
  "PISAC",
  "PLAZA LA TOMILLA",
  "PLAZA NORTE ENTREGAS",
  "POCOLLAY",
  "POMALCA",
  "PRO",
  "PROLONG LUIS MASSARO",
  "PUCALLPA CO FEDERICO BASADRE",
  "PUENTE ARICA",
  "PUENTE LURIN",
  "PUENTE NUEVO",
  "PUENTE SANTA ANITA",
  "PUENTE VIRU",
  "PUNCHANA",
  "PUNTA HERMOSA",
  "QUEBRADA LAS LECHUZAS CO",
  "QUILLABAMBA",
  "REAL PLAZA SALAVERRY",
  "REP. DE PANAMA",
  "REQUE",
  "RIMAC AV. AMANCAES",
  "RIMAC GUARDIA REPUBLICANA CDRA. 9",
  "RIOJA",
  "SALAS ICA",
  "SALAVERRY HUACHO CO",
  "SALCEDO",
  "SAN AGUSTIN DE CAJAS",
  "SAN ANTONIO",
  "SAN CARLOS HUANCAYO",
  "SAN CLEMENTE",
  "SAN IGNACIO",
  "SAN JERONIMO",
  "SAN JOSE DE SISA",
  "SAN JUAN BAUTISTA",
  "SAN JUAN DE MARCONA",
  "SAN MARCOS",
  "SAN MARTIN BELLAVISTA",
  "SAN MIGUEL CAJAMARCA",
  "SAN PABLO  CAJAMARCA",
  "SAN PEDRO DE LLOC",
  "SAN RAMÓN",
  "SANTA",
  "SANTA CLARA",
  "SANTA MARÍA DE HUACHIPA",
  "SANTA ROSA",
  "SANTO DOMINGO",
  "SANTO TOMAS",
  "SAPOSOA",
  "SATIPO",
  "SAYAN",
  "SECHURA",
  "SEGUNDA JERUSALEN",
  "SICUANI AV MANUEL CALLO",
  "SICUANI CO OVALO SAN ANDRES",
  "SJL- LAS FLORES",
  "SJL-AV.PROCERES",
  "SMP-AV. PROCERES",
  "SORITOR",
  "SULLANA CO ZONA INDUSTRIAL",
  "SULLANA SANTA ROSA",
  "SUNAMPE  CO",
  "SUPE",
  "SURCO MATEO PUMACAHUA",
  "TACALA",
  "TACNA CIUDAD NUEVA",
  "TACNA CO AV. JORGE BASADRE",
  "TALARA  CO ASOC CALIFORNIA",
  "TALARA ALTA 9 DE OCTUBRE",
  "TALARA BAJA PARQUE 22",
  "TAMBO GRANDE",
  "TAMBOPATA AV CIRCUNVALACION",
  "TAMBOPATA AV LA JOYA CO",
  "TARAPOTO CO JR ALFONSO UGARTE",
  "TARAPOTO JR. SARGENTO LOREZ",
  "TARAPOTO LA BANDA DE SHILCAYO",
  "TARMA",
  "TEMBLADERA  CAJAMARCA",
  "TERMINAL JAUJA",
  "TERMINAL LOS ANDES",
  "TICA TICA",
  "TINGO MARÍA - LEONCIO PRADO",
  "TINGO MARIA CO BUENOS AIRES",
  "TRES DE OCTUBRE",
  "TRUJILLO LA PERLA",
  "TUCUME",
  "TUMAN",
  "TUMBES - AV ARICA",
  "TUMBES CO - PANAMERICANA NORTE KM 2360",
  "TUMBES PUYANGO",
  "TUNGASUCA",
  "UCHIZA",
  "UCHUMAYO",
  "URB MANUEL PRADO",
  "URB SANTA ELVIRA",
  "URB. BANCOPATA AV. INDUSTRIAL",
  "URB. REPARTICIÓN",
  "URCOS",
  "VELASCO ASTETE",
  "VIA EXPRESA SUR",
  "VILLA RICA",
  "VILLA SAN FRANCISCO",
  "VIÑANIS",
  "VIRU CENTRO",
  "VISTA ALEGRE CO",
  "WICHANZAO",
  "YARINACOCHA  AV UNIVERSITARIA",
  "YARINACOCHA CENTRO",
  "YUNGAY",
  "YURA",
  "YURIMAGUAS",
  "ZAMACOLA",
  "ZAPALLAL",
  "ZARUMILLA",
  "ZORRITOS",
  "01 DE MAYO",
];

const _n = (s: string) => String(s ?? "").toUpperCase().normalize("NFD")
  .replace(/[\u0300-\u036f]/g, "").replace(/[^A-Z0-9 ]/g, " ")
  .replace(/\bSHALOM\b/g, " ").replace(/\s+/g, " ").trim();

export function candidatasAgencia(texto: string): string[] {
  const t = _n(texto);
  if (!t) return [];
  const exact = AGENCIAS_SHALOM.filter((a) => _n(a) === t);
  if (exact.length) return exact;
  return AGENCIAS_SHALOM.filter((a) => { const na = _n(a); return na && (t.includes(na) || na.includes(t)); });
}

export function sedeReconocida(sede: string, ciudad: string): string | null {
  const s = String(sede ?? "").trim();
  // ⚠️ Esta lista es la columna DESTINO del Excel de carga de Shalom: es real, pero
  // PARCIAL y puede quedar desactualizada — mientras no exista la API, no hay forma de
  // saber cuántas oficinas tiene de verdad una ciudad. Que Chiclayo aparezca acá con una
  // sola NO prueba que Shalom tenga una sola: prueba que la lista conoce una. Por eso
  // "la ciudad resuelve a una única agencia" dejó de contar como certeza. Lo único que
  // confirma el destino es que el CLIENTE haya nombrado una oficina que sí está en la
  // lista; todo lo demás se marca para que un humano lo coordine con él.
  if (!s) {
    return String(ciudad ?? "").trim()
      ? "no dijo la oficina — confírmala con él antes de despachar"
      : "falta la sede/agencia de destino — confírmala";
  }
  const cs = candidatasAgencia(s);
  if (cs.some((a) => _n(a) === _n(s))) return null;      // nombró una agencia tal cual
  const cn = _n(ciudad);
  const esLaCiudad = !!cn && _n(s).includes(cn);
  // Su texto apunta a UNA agencia concreta de la lista ("miraflores" → MIRAFLORES
  // CHICLAYO): eso sí identifica una oficina. Decir la ciudad no identifica ninguna,
  // porque puede haber otras que la lista no trae.
  if (cs.length === 1 && !esLaCiudad) return null;
  if (cs.length > 1) return "hay varias oficinas Shalom que calzan — confirma la exacta";
  if (esLaCiudad) return "solo dijo la ciudad — confirma con él a qué oficina va";
  return "dijo una oficina que no está en la lista — confírmasela antes de despachar";
}