// ═══════════════════════════════════════════════════════════════════
// Nodo · shalom-agencias.ts — las 552 agencias de Shalom, con su ubicación.
//
// Reemplaza a la lista de 486 nombres sueltos que salía de la columna DESTINO
// del Excel de carga. Aquella no solo estaba incompleta: era ENGAÑOSA, porque
// tenía una sola entrada para Chiclayo y el motor dedujo de ahí que Chiclayo
// tiene una sola oficina. Tiene 14. Una clienta pidió "la sede que está en la
// plaza", el sistema no la reconoció y despachó a otra: existe, es CALLE TACNA
// 1095, a una cuadra de la Plaza de Armas.
//
// Cada agencia trae dónde queda de verdad, así que ahora se puede responder
// "¿qué oficinas hay en mi ciudad?" sin inventar, y distinguir entre "dijo una
// oficina que no existe" y "dijo una ciudad donde hay varias".
//
//   l   = lugar: el NOMBRE de la agencia (es lo que viaja al Excel del courier)
//   d/p/t = departamento / provincia / distrito
//   dir = dirección (primer tramo; el resto repetía distrito y provincia)
//   ref = la referencia de Shalom ("a espaldas del Makro", "al costado de la
//         comisaría"): la trae el 88% y es lo que de verdad le hace reconocer
//         la oficina al cliente, que casi nunca se sabe la dirección formal
//   a   = hace envío aéreo (483 de 552)
//
// panel/courier/listas.json — lo que viaja al Excel del courier — es el ESPEJO de
// este archivo y tiene las mismas 552. Se comprobó con una carga REAL que Shalom
// acepta los nombres nuevos: registró sin error un envío a HUARAZ CO, que su
// plantilla vieja no traía. Si se regenera uno, regenerar el otro.
//
// Sigue sin haber API de Shalom: esto es un volcado de su directorio, tomado el
// 2026-08-29. Vale para CONFIRMAR lo que dice el cliente, no para jurar que una
// oficina existe hoy. Para regenerarlo con un volcado nuevo está el script
// scratchpad/gen-agencias.pl.
// ═══════════════════════════════════════════════════════════════════

export type Agencia = {
  l: string;
  d: string;
  p: string;
  t: string;
  dir?: string;
  ref?: string;
  a?: 1;
};

export const AGENCIAS: Agencia[] = [
  {l:"BAGUA CAPITAL",d:"AMAZONAS",p:"BAGUA",t:"BAGUA",dir:"JR. AMAZONAS C-9 MZ. 126 LT. 25",ref:"FRENTE AL PARQUE JERUSALEN Y/O COSTADO DE AVICOLA YACEG",a:1},
  {l:"PEDRO RUIZ",d:"AMAZONAS",p:"BONGARA",t:"JAZAN",dir:"AV. SACSAHUAMAN N° 513 - PEDRO RUIZ",ref:"A MEDIA CUADRA DE LA UGEL",a:1},
  {l:"CHACHAPOYAS CO DOS DE MAYO",d:"AMAZONAS",p:"CHACHAPOYAS",t:"CHACHAPOYAS",dir:"JR. DOS DE MAYO CDRA. 15 S/N CHACHAPOYAS",ref:"JUNTO A TERMINAL DE COMBIS ETSA",a:1},
  {l:"CHACHAPOYAS JR GRAU",d:"AMAZONAS",p:"CHACHAPOYAS",t:"CHACHAPOYAS",dir:"JR. GRAU 270",ref:"JUNTO A LA AGENCIA DE VIAJES MONTEVERDE",a:1},
  {l:"LUYA",d:"AMAZONAS",p:"LUYA",t:"LUYA",dir:"JR. RAMÓN CASTILLA S/N",ref:"ENTRE EL COLEGIO SECUNDARIO RAMÓN CASTILLA Y EL JR. JOSÉ GÁLVEZ, A MEDIA CDRA. DEL AGENTE",a:1},
  {l:"BAGUA GRANDE",d:"AMAZONAS",p:"UTCUBAMBA",t:"BAGUA GRANDE",dir:"AV. CHACHAPOYAS 1094 SECTOR GONCHILLO",ref:"A 2 CUADRAS DE LA CLÍNICA SEÑOR DE LOS MILAGROS",a:1},
  {l:"CARHUAZ",d:"ANCASH",p:"CARHUAZ",t:"CARHUAZ",dir:"CARRETERA CENTRAL 00S/N CENT CARHUAZ - CARHUAZ - ÁNCASH",ref:"MEDIA CUADRA ANTES DE LLEGAR AL ESTADIO MUNICIPAL CAPITAN CARLOS MEJIA",a:1},
  {l:"CASMA",d:"ANCASH",p:"CASMA",t:"CASMA",dir:"AV. MIGUEL GRAU MZ. D 4 LT. 1 CASMA - ANCASH",ref:"FRENTE AL JARDÍN DE INFANCIA",a:1},
  {l:"HUARAZ CO",d:"ANCASH",p:"HUARAZ",t:"HUARAZ",dir:"AV. 27 DE NOVIEMBRE CDRA. 20 S/N - VILLON BAJO",ref:"AL COSTADO DEL GRIFO PRIMAX",a:1},
  {l:"HUARMEY",d:"ANCASH",p:"HUARMEY",t:"HUARMEY",dir:"CARR. PANAMERICANA NORTE N° KM 293 SECT. PANAMERICANA HUAR",ref:"A 4 CDRAS. DEL TERMINAL TERRESTRE DE SUR A NORTE",a:1},
  {l:"CARAZ",d:"ANCASH",p:"HUAYLAS",t:"CARAZ",dir:"AV. 9 DE OCTUBRE N° 259 - HUAYLAS",ref:"AL COSTADO DE LA EMPRESA MÓVIL TOURS",a:1},
  {l:"AV  JOSE GALVEZ",d:"ANCASH",p:"SANTA",t:"CHIMBOTE",dir:"AV. JOSÉ GÁLVEZ 791",ref:"A 1 CDRA. ANTES DE LLEGAR AL PUENTE GÁLVEZ",a:1},
  {l:"AV ENRIQUE MEIGGS",d:"ANCASH",p:"SANTA",t:"CHIMBOTE",dir:"Av. Enrique Meiggs N° 2457.",a:1},
  {l:"AV. LOS PESCADORES CO",d:"ANCASH",p:"SANTA",t:"CHIMBOTE",dir:"PAR. PARCELA N° 16757 - E SECTOR LA PERLA TRES CABEZAS - A",ref:"FRENTE AL ESTADIO CENTENARIO",a:1},
  {l:"AV. PACÍFICO BELEN",d:"ANCASH",p:"SANTA",t:"NUEVO CHIMBOTE",dir:"AA.HH. BELEN MZ O LT 28 - NUEVO CHIMBOTE - SANTA - ANCASH",ref:"FRENTE AL GRIFO DOXA",a:1},
  {l:"GARATEA",d:"ANCASH",p:"SANTA",t:"NUEVO CHIMBOTE",dir:"URB. NICOLAS GARATEA MZ. 100 LT. 24 - NUEVO CHIMBOTE - SAN",ref:"FRENTE AL PARADERO AUTOS N.- GARATEA",a:1},
  {l:"OVALO DE LA FAMILIA",d:"ANCASH",p:"SANTA",t:"NUEVO CHIMBOTE",dir:"Urbanización José Carlos Mariategui (ex UNICRETO) mz R 3 l",ref:"A una cuadra del óvalo la familia",a:1},
  {l:"SANTA",d:"ANCASH",p:"SANTA",t:"SANTA",dir:"PANAMERICANA NORTE KM 442 - B",ref:"AL LADO DE LA FERRETERIA LA LLAVE",a:1},
  {l:"TRES DE OCTUBRE",d:"ANCASH",p:"SANTA",t:"NUEVO CHIMBOTE",dir:"AV. JOSÉ PARDO MZ. K",ref:"FRENTE AL ÓVALO LAS AMÉRICAS",a:1},
  {l:"YUNGAY",d:"ANCASH",p:"YUNGAY",t:"YUNGAY",dir:"JR. INDUSTRIAL",ref:"AL COSTADO DEL TERMINAL TERRESTRE Y LA TAPICERIA FREDY",a:1},
  {l:"ABANCAY",d:"APURIMAC",p:"ABANCAY",t:"ABANCAY",dir:"AV. PANAMERICANA S/N - ABANCAY - APURÍMAC",ref:"A 100 METROS DE LA COMISARÍA DE BELLAVISTA, AL COSTADO DE MADERERA VEGA",a:1},
  {l:"ANDAHUAYLAS",d:"APURIMAC",p:"ANDAHUAYLAS",t:"ANDAHUAYLAS",dir:"AV. MALINAS 1355 POCHCCOTA",ref:"AL COSTADO DE LA EX CANCHA EL CENTENARIO O ALTURA DE LA UNIVERSIDAD UNSAAC",a:1},
  {l:"CHALLHUAHUACHO",d:"APURIMAC",p:"COTABAMBAS",t:"CHALLHUAHUACHO",dir:"BARRIO WICHAYPAMPA LT. 13 - 15 - 16",ref:"A DOS CDRAS DEL TERMINAL TERRESTRE DE CHALLHUAHUACHO / A ESPALDAS DEL TALLER E&L",a:1},
  {l:"AEROPUERTO AREQUIPA",d:"AREQUIPA",p:"AREQUIPA",t:"AREQUIPA",dir:"Aeropuerto Internacional Alfredo Rodríguez"},
  {l:"ASOC LAS FLORES -  AV 54",d:"AREQUIPA",p:"AREQUIPA",t:"CERRO COLORADO",dir:"ASOC. VIVIENDA INTERES SOCIAL ALDO MORO MZ. C LT. 21",ref:"AL LADO DEL SISTEMA ELÉCTRICO EL PROFE",a:1},
  {l:"ASOC. NUEVO HORIZONTE - AV. 54",d:"AREQUIPA",p:"AREQUIPA",t:"CERRO COLORADO",dir:"NUEVO HORIZONTE MZ.H LOTE 12 - CERRO COLORADO - AREQUIPA",ref:"CON AV.54 A CUATRO CDRAS. DE INKAFARMA",a:1},
  {l:"AUTOPISTA LA JOYA",d:"AREQUIPA",p:"AREQUIPA",t:"CERRO COLORADO",dir:"ASOC. URBANIZADORA PERUARBO SECTOR PERU ZONA I MZ. B4 LT.",ref:"AUTOPISTA AREQUIPA - LA JOYA, A DOS CDRAS. DEL SAUNA CANDAMO",a:1},
  {l:"AV AUGUSTO SALAZAR BONDY",d:"AREQUIPA",p:"AREQUIPA",t:"ALTO SELVA ALEGRE",dir:"AUGUSTO SALAZAR BONDY MZ J LT 4 ALTO SELVA ALEGRE - AREQUI",ref:"A MEDIA CDRA. DE LA IGLESIA GUADALUPE",a:1},
  {l:"AV CHARCANI",d:"AREQUIPA",p:"AREQUIPA",t:"CAYMA",dir:"AV. CHARCANI 401 ASOC. JOSE OLAYA",ref:"FRENTE AL COLEGIO MENDEL",a:1},
  {l:"AV JESUS",d:"AREQUIPA",p:"AREQUIPA",t:"PAUCARPATA",dir:"AV. JESÚS N° 1100 PAUCARPATA – AREQUIPA",ref:"CON ESQUINA ARTURO VILLEGAS N° 101",a:1},
  {l:"AV LIMA",d:"AREQUIPA",p:"AREQUIPA",t:"ALTO SELVA ALEGRE",dir:"AV. LIMA N° 406 – ALTO SELVA ALEGRE - AREQUIPA",ref:"ESQUINA CON AV. OBRERA CUADRA 20",a:1},
  {l:"AV LOS INCAS",d:"AREQUIPA",p:"AREQUIPA",t:"CERRO COLORADO",dir:"AV. LOS INCAS N° 604 SEMIRURAL PACHACUTEC – CERRO COLORADO",ref:"ESQUINA CON CALLE SAN MARTIN SEMIRURAL PACHACUTEC",a:1},
  {l:"AV PARRA 379",d:"AREQUIPA",p:"AREQUIPA",t:"AREQUIPA",dir:"AV. PARRA 379 - Arequipa",a:1},
  {l:"AV PUMACAHUA",d:"AREQUIPA",p:"AREQUIPA",t:"CERRO COLORADO",dir:"URB. SAN FELIPE AV PUMACAHUA LT 14",ref:"A DOS CDRAS. ANTES DE LLEGAR AL METRO CENCOSUD / EX NOTARIA CONCHA REVILLA",a:1},
  {l:"AV SOCABAYA - LOS TORITOS",d:"AREQUIPA",p:"AREQUIPA",t:"SOCABAYA",dir:"AV. SOCABAYA 301 - URB. SAN MARTÍN DE SOCABAYA",ref:"AL FRENTE DEL PARQUE VICTOR BARRIGA",a:1},
  {l:"AV. HORACIO ZEVALLOS",d:"AREQUIPA",p:"AREQUIPA",t:"SOCABAYA",dir:"ASENTAMIENTO URBANO MUNICIPAL HORACIO ZEBALLOS GAMEZ SECTO",ref:"AL COSTADO DEL COLEGIO JOULE Y/O 2 CDRAS. DEL PENAL DE SOCABAYA",a:1},
  {l:"CIUDAD MUNICIPAL",d:"AREQUIPA",p:"AREQUIPA",t:"CERRO COLORADO",dir:"MZ. A",ref:"AL COSTADO DEL GRIFO PRIMAX",a:1},
  {l:"CONGATA",d:"AREQUIPA",p:"AREQUIPA",t:"UCHUMAYO",dir:"URB. EL CARMEN M. E. LT. 1 CONGATA DEL DISTRITO UCHUMAYO -",ref:"A DOS CDRAS. DE LA COMISARIA CONGATA",a:1},
  {l:"EL CRUCE LA JOYA",d:"AREQUIPA",p:"AREQUIPA",t:"LA JOYA",dir:"LATERAL 12 C LT. 32",ref:"AL COSTADO DEL GRIFO PRIMAX DE LA JOYA",a:1},
  {l:"JACOBO HUNTER",d:"AREQUIPA",p:"AREQUIPA",t:"JACOBO HUNTER",dir:"CALLE ARGENTINA # 405 - A",ref:"FRENTE AL CAJERO DE CAJA AREQUIPA Y ESQUINA CON EL BANCO CAJA AREQUIPA",a:1},
  {l:"MALL LAMBRAMANI",d:"AREQUIPA",p:"AREQUIPA",t:"AREQUIPA",dir:"AV. LAMBRAMANI 325",ref:"DENTRO DEL MALL LAMBRAMANI (SOTANO PISO -4)",a:1},
  {l:"MARIANO MELGAR",d:"AREQUIPA",p:"AREQUIPA",t:"MARIANO MELGAR",dir:"CALLE ANCASH N° 202 - MARIANO MELGAR",ref:"A LA ALTURA DEL COLISEO DEL NIÑO",a:1},
  {l:"MIRAFLORES AREQUIPA",d:"AREQUIPA",p:"AREQUIPA",t:"MIRAFLORES",dir:"URB. RESIDENCIAL FELIPE SANTIAGO SALAVERRY - CALLE TENIENT",ref:"A MEDIA CDRA. DE LA COMPAÑIA DE BOMBERO DE MIRAFLORES",a:1},
  {l:"PLAZA LA TOMILLA",d:"AREQUIPA",p:"AREQUIPA",t:"CAYMA",dir:"AV. RAMÓN CASTILLA N° 1000 - B LA TOMIllA CAYMA - REFERENC",ref:"EN LA MISMA PLAZA TOMIlla",a:1},
  {l:"URB MANUEL PRADO",d:"AREQUIPA",p:"AREQUIPA",t:"PAUCARPATA",dir:"CALLE BELÉN N°100 - A URB. MANUEL PRADO - PAUCARPATA REFER",ref:"A ESPALDAS DEL CC. MALL AVENTURA PORONGOCHE",a:1},
  {l:"VARIANTE UCHUMAYO CO",d:"AREQUIPA",p:"AREQUIPA",t:"SACHACA",dir:"VARIANTE DE UCHUMAYO KM 4.5 VALLE CHILI SECTOR ALTO CURAL",ref:"A 50 MTS. DEL ÓVALO VOLVO VARIANTE UCHUMAYO",a:1},
  {l:"YURA",d:"AREQUIPA",p:"AREQUIPA",t:"YURA",dir:"MZ. O LT. 4 ZNA 2 CIUDAD DE DIOS - YURA - AREQUIPA",ref:"CARRETERA YURA",a:1},
  {l:"ZAMACOLA",d:"AREQUIPA",p:"AREQUIPA",t:"CERRO COLORADO",dir:"CALLE YAVARÍ 507 B - ZAMACOLA - CERRO COLORADO – AREQUIPA",ref:"A UNA CUADRA DE LA POSTA DE ZAMACOLA (MARCISA CAMPOS)",a:1},
  {l:"CAMANA",d:"AREQUIPA",p:"CAMANA",t:"CAMANA",dir:"CALLE AGUSTÍN GAMARRA N° 451",ref:"AL FRENTE DEL DELIVEY CASERITOS",a:1},
  {l:"CHALA",d:"AREQUIPA",p:"CARAVELI",t:"CHALA",dir:"AV. EMANCIPACION NRO. S/N MZ. 78 LT. 10. REF. A MEDIA CDRA",ref:"A MEDIA CDRA. DEL PARQUE DEL NIÑO CHALINO"},
  {l:"APLAO",d:"AREQUIPA",p:"CASTILLA",t:"APLAO",dir:"UBICA EN LA MANZANA X1",ref:"A UNA CDRA. DE MINISTERIAL PÚBLICO FISCALÍA",a:1},
  {l:"AV COLONIZADORES  CO",d:"AREQUIPA",p:"CAYLLOMA",t:"MAJES",dir:"AV. LOTE COLONIZADORES. 4 PARCELA 180",ref:"A MEDIA CDRA. DEL GRIFO EL EJE",a:1},
  {l:"CALLE YARABAMBA",d:"AREQUIPA",p:"CAYLLOMA",t:"MAJES",dir:"CALLE YARABAMBA",ref:"A MEDIA CDRA. DE LA NOTARIA TERÁN BEJAR",a:1},
  {l:"CERCADO MOLLENDO",d:"AREQUIPA",p:"ISLAY",t:"MOLLENDO",dir:"CALLE DEAN VALDIVIA 388 CERCADO",ref:"ESQUINA CON BLONDEL"},
  {l:"COCACHACRA",d:"AREQUIPA",p:"ISLAY",t:"COCACHACRA",dir:"CENTRO POBLADO COCACHACRA MZ. N5 SUB-LOTE 5B CALLE DEAN VA",ref:"DEL PARQUE SAN FRANCISCO UNA CDRA. HACIA ABAJO",a:1},
  {l:"MATARANI",d:"AREQUIPA",p:"ISLAY",t:"ISLAY",dir:"ASENTAMIENTO HUMANO. PUERTO NUEVO MZ. I LT. 18 AV. BELLO H",ref:"FRENTE AL PARQUE ECOLÓGICO",a:1},
  {l:"MOLLENDO CO",d:"AREQUIPA",p:"ISLAY",t:"MOLLENDO",dir:"MARISCAL CASTILLA 472 –A",ref:"AL COSTADO DE CEI “MI CARRUSEL”",a:1},
  {l:"AEROPUERTO AYACUCHO",d:"AYACUCHO",p:"HUAMANGA",t:"AYACUCHO",dir:"Aeropuerto Internacional Alfredo Mendívil Duarte de Ayacuc"},
  {l:"AYACUCHO CO",d:"AYACUCHO",p:"HUAMANGA",t:"AYACUCHO",dir:"AA.HH COMPLEJO ARTESANAL T1 LT1 - ayacucho - rEFERENCIA :",ref:"a una cuadra de la puerta 2 del terminal terrestre libertadores de AMÉRICA",a:1},
  {l:"CARMEN ALTO",d:"AYACUCHO",p:"HUAMANGA",t:"CARMEN ALTO",dir:"ASENTAMIENTO HUMANO CARMEN ALTO MZ B1 LOTE 9 ZONA II ACUCH",ref:"A 1 CUADRA DE LA MUNICIPALIDAD DE CARMEN ALTO",a:1},
  {l:"JESUS NAZARENO",d:"AYACUCHO",p:"HUAMANGA",t:"JESUS NAZARENO",dir:"JR. JOSÉ MARÍA EGUREN 451 - JESUS NAZARENO - HUAMANGA - AY",ref:"CRUCE CON JR. MARIANO MELGAR",a:1},
  {l:"SAN JUAN BAUTISTA",d:"AYACUCHO",p:"HUAMANGA",t:"SAN JUAN BAUTISTA",dir:"AV. VENEZUELA N° 431 – URB. APROVISA",ref:"ALTURA DEL HOSTAL LA ORIENTAL, CERCA AL SEGURO DE ESSALUD",a:1},
  {l:"HUANTA",d:"AYACUCHO",p:"HUANTA",t:"HUANTA",dir:"JR. GERVASIO SANTILLANA N°976 - HUANTA - AYACUCHO. REF",a:1},
  {l:"CAJABAMBA",d:"CAJAMARCA",p:"CAJABAMBA",t:"CAJABAMBA",dir:"JR. LARA N° 100",ref:"A UNA CDRA. DEL COMPLEJO DEPORTIVO “SANTA ANA”",a:1},
  {l:"AEROPUERTO CAJAMARCA",d:"CAJAMARCA",p:"CAJAMARCA",t:"CAJAMARCA",dir:"aeropuerto MAYOR GENERAL FAP ARMANDO REVOREDO IGLESIAS"},
  {l:"BARRIO SAN JOSE",d:"CAJAMARCA",p:"CAJAMARCA",t:"CAJAMARCA",dir:"Jr. Chanchamayo N° 1162 - Barrio San José Cajamarca",ref:"Paralela Con Jr. Huancavelica y Jr. Sara Macdougall",a:1},
  {l:"BARRIO SAN MARTÍN",d:"CAJAMARCA",p:"CAJAMARCA",t:"CAJAMARCA",dir:"JIRÓN LOS GLADIOLOS N° 336 BARRIO SAN MARTÍN",ref:"A LA ALTURA DE LA CDRA. 13 DE LA VÍA DE EVITAMIENTO SUR",a:1},
  {l:"BAÑOS DEL INCA",d:"CAJAMARCA",p:"CAJAMARCA",t:"LOS BANOS DEL INCA",dir:"JR. CAHUIDE N° 242 – LOTIZ. HURTADO MILLER – BAÑOS DEL INC",ref:"A ESPALDAS DE SENATI Y A UNA CDRA. DE LA BASE DE SERENAZGO DE BAÑOS DEL INCA",a:1},
  {l:"CAJAMARCA CO",d:"CAJAMARCA",p:"CAJAMARCA",t:"CAJAMARCA",dir:"Av. Independencia N° 787 Barrio Santa Elena",a:1},
  {l:"CAJAMARCA HORACIO ZEVALLOS",d:"CAJAMARCA",p:"CAJAMARCA",t:"CAJAMARCA",dir:"JR. EMILIO BARRANTES MZ X LOTE 3 URB. HORACIO ZEVALLOS - C",ref:"A UNA CUADRA DE LA UNIVERSIDAD PRIVADA DEL NORTE (UPN) Y VÍA DE EVITAMIENTO NORTE CUADRA",a:1},
  {l:"HUAMBOCANCHA BAJA",d:"CAJAMARCA",p:"CAJAMARCA",t:"CAJAMARCA",dir:"MZ. A LOTE S/N – BARRIO HUAMBOCANCHA BAJA – CAJAMARCA",ref:"A UNA CDRA. DEL PARADERO DE LA P13/AL COSTADO DEL CAMPO DEPORTIVO EL PATRIARCA",a:1},
  {l:"HUARACLLA",d:"CAJAMARCA",p:"CAJAMARCA",t:"JESUS",dir:"MZ. A LOTE S/N CP HUARACLLA - JESUS - CAJAMARCA",ref:"A UNA CDRA. DE LA I.E. JOSÉ OLAYA BALANDRA",a:1},
  {l:"CELENDIN",d:"CAJAMARCA",p:"CELENDIN",t:"CELENDIN",dir:"JR. PEDRO ORTIZ MONTOYA 148",ref:"ESQUINA CON AV. AMAZONAS",a:1},
  {l:"CHOTA",d:"CAJAMARCA",p:"CHOTA",t:"CHOTA",dir:"AV. FRAY JOSÉ ARANA N 805 - REFERENCIA : frente al termina",ref:"frente al terminal angel divino",a:1},
  {l:"CHILETE - AGENTE",d:"CAJAMARCA",p:"CONTUMAZA",t:"CHILETE",dir:"JR. SANTA ROSA N° 121",ref:"A UNA CDRA. DEL TERRAPUERTO Y A 100 MTS. DEL PUENTE DE INGRESO A CHILETE",a:1},
  {l:"TEMBLADERA  CAJAMARCA",d:"CAJAMARCA",p:"CONTUMAZA",t:"YONAN",dir:"JR. BOLOGNESI S/N – TEMBLADERA - YONAN - CONTUMAZÁ - CAJAM",ref:"AL FRENTE DEL PARQUE VÍCTOR RAÚL HAYA DE LA TORRE",a:1},
  {l:"CUTERVO",d:"CAJAMARCA",p:"CUTERVO",t:"CUTERVO",dir:"av. SALOMÓN VILCHEZ murga S/N. CDRA 9 REFERENCIA : FRENTE",ref:"FRENTE A LA CLÍNICA CUTERVO",a:1},
  {l:"BAMBAMARCA",d:"CAJAMARCA",p:"HUALGAYOC",t:"BAMBAMARCA",dir:"AV. TUPAC AMARU 1105",ref:"AL COSTADO DEL PARADERO AL CUMBE",a:1},
  {l:"JAEN CO",d:"CAJAMARCA",p:"JAEN",t:"JAEN",dir:"AV. PAKAMMUROS CUADRA 6 S/N - referencia: ESQUINA CON CALL",ref:"ESQUINA CON CALLE LIBERTAD N° 490"},
  {l:"SAN IGNACIO",d:"CAJAMARCA",p:"SAN IGNACIO",t:"SAN IGNACIO",dir:"PASAJE TRES N° 113 URB SANTA ROSA",ref:"FRENTE AL ESTADO MUNICIPAL"},
  {l:"SAN MARCOS",d:"CAJAMARCA",p:"SAN MARCOS",t:"PEDRO GALVEZ",dir:"JR. ADOLFO AMORIN BUENO N° 140 SAN MARCOS – CAJAMARCA",ref:"AL FRENTE DE LA PLAZA AGROPECUARIA",a:1},
  {l:"SAN MIGUEL CAJAMARCA",d:"CAJAMARCA",p:"SAN MIGUEL",t:"SAN MIGUEL",dir:"JR. BOLOGNESI N° 717 – SAN MIGUEL – CAJAMARCA - CAJAMARCA",ref:"AL COSTADO DEL COLISEO Y EL PARADERO DE LLAPA Y COCHÁN",a:1},
  {l:"SAN PABLO  CAJAMARCA",d:"CAJAMARCA",p:"SAN PABLO",t:"SAN PABLO",dir:"JR. TNT. LORENZO IGLESIA N° 910 - SAN PABLO – CAJAMARCA -",ref:"A MEDIA CDRA. DEL HOSPITAL SAN PABLO",a:1},
  {l:"AEROPUERTO CALLAO",d:"CALLAO",p:"CALLAO",t:"CALLAO",dir:"AEROPUERTO INTERNACIONAL JORGE CHAVEZ"},
  {l:"AV  QUILCA",d:"CALLAO",p:"CALLAO",t:"CALLAO",dir:"UNIDAD INMOBILIARIA N° 1",ref:"CRUCE CON CALLE 1, FRENTE A LA IGLESIA DE TESTIGOS DE JEHOVÁ",a:1},
  {l:"AV BERTELLO CALLAO",d:"CALLAO",p:"CALLAO",t:"CALLAO",dir:"AV. ALEJANDRO BERTELLO BOLLATI MZ. B LT. 20 Y 21 – URB. PR",ref:"FRENTE AL MERCADO COSTA AZUL",a:1},
  {l:"AV SAENZ PEÑA",d:"CALLAO",p:"CALLAO",t:"CALLAO",dir:"AV. SAENZ PEÑA N° 414 - 416 - CALLAO - CALLAO",ref:"CRUCE CON AV. MARCO POLO",a:1},
  {l:"BELLAVISTA CALLAO",d:"CALLAO",p:"CALLAO",t:"BELLAVISTA",dir:"AV. ELMER FAUCETT 1641 - URB. JARDINES VIRÚ MZ. B LT 46",ref:"A 2 CUADRAS DEL CRUCE DE AV. FAUCETT CON AV. VENEZUELA",a:1},
  {l:"CALLAO FAUCETT",d:"CALLAO",p:"CALLAO",t:"CALLAO",dir:"AV. ELMER FAUCETT N° 492",a:1},
  {l:"MI PERU",d:"CALLAO",p:"CALLAO",t:"MI PERU",dir:"V. VICTOR RAUL HAYA DE LA TORRE MZ. A LT. 02 ASENTAMIENTO",ref:"CRUCE CON AV. AREQUIPA",a:1},
  {l:"OUTLET ARAUCO FAUCETT",d:"CALLAO",p:"CALLAO",t:"CALLAO",dir:"AV. ELMER FAUCETT 3443 - CALLAO",ref:"AL COSTADO DEL AEROPUERTO JORGE CHÁVEZ"},
  {l:"OVALO LA PERLA",d:"CALLAO",p:"CALLAO",t:"LA PERLA",dir:"AV. LA MARINA 530",ref:"A 3 CUADRAS DEL ÓVALO DE LA PERLA",a:1},
  {l:"PACHACUTEC  AV 150",d:"CALLAO",p:"CALLAO",t:"VENTANILLA",dir:"AV. 150 IZQUIERDA MZ. W2 LT. 01 PROYECTO PILOTO NUEVO PACH",ref:"A 1 CDRA. DEL CRUCE AV. CAMINO DEL INCA",a:1},
  {l:"PACHACUTEC PDRO CHINITAS",d:"CALLAO",p:"CALLAO",t:"VENTANILLA",dir:"AV. 225 MZ. H SUB LT. T. 11 - ASOC PROY. ESP. CIUDAD PACHA",ref:"A 1 CDRA. DEL CRUCE CON AV. LOS PROYECTISTAS, VENTANILLA - LIMA - LIMA",a:1},
  {l:"PACHACUTEC PDRO VC",d:"CALLAO",p:"CALLAO",t:"VENTANILLA",dir:"AV. 225 MZ F LOTE 2 SECTOR A GRUPO RESIDENCIAL A2 - PROYEC",ref:"FRENTE AL CENTRO DE SALUD 3 DE FEBRERO",a:1},
  {l:"PARAD.  LOS LICENCIADOS",d:"CALLAO",p:"CALLAO",t:"VENTANILLA",dir:"CALLE 19",ref:"AL COSTADO DE LUBRICENTRO PABLITO ROMERO",a:1},
  {l:"ANTA IZCUCHACA",d:"CUSCO",p:"ANTA",t:"ANTA",dir:"PARQUE DEL CARMEN LT. 1 MZ. B 2",ref:"PARADERO CARMEN, PISTA PRINCIPAL IZCUCHACA",a:1},
  {l:"CUSCO CALCA",d:"CUSCO",p:"CALCA",t:"CALCA",dir:"AV. VILCANOTA MZ. A LT 4 CALCA - CUSCO",ref:"FRENTE AL GRIFO PETRO PERÚ O EL ÓVALO PUMA - ENTRADA DE CALCA",a:1},
  {l:"PISAC",d:"CUSCO",p:"CALCA",t:"PISAC",dir:"AV VILCANOTA S/N",ref:"A MEDIA CDRA. DEL PUENTE DE PISAC / CARRETERA A TARAY",a:1},
  {l:"COMBAPATA",d:"CUSCO",p:"CANCHIS",t:"COMBAPATA",dir:"AV. SEÑOR DE HUANCA S/N - COMBAPATA - CANCHIS - CUSCO",ref:"AL COSTADO DEL GRIFO SEÑOR DE QOYLLURITI - A ORILLAS DE LA MISMA CARRETERA A SICUANI",a:1},
  {l:"SICUANI AV MANUEL CALLO",d:"CUSCO",p:"CANCHIS",t:"SICUANI",dir:"JR. INAMBARI NRO. 208",ref:"AL FRENTE DEL BCP Y DE CAJA PIURA",a:1},
  {l:"SICUANI CO OVALO SAN ANDRES",d:"CUSCO",p:"CANCHIS",t:"SICUANI",dir:"PROLONG. AV. AREQUIPA 1010 S/N",ref:"AL COSTADO DEL GRIFO GUADALUPE EN EL ÓVALO SAN ANDRÉS",a:1},
  {l:"SANTO TOMAS",d:"CUSCO",p:"CHUMBIVILCAS",t:"SANTO TOMAS",dir:"CALLE BOLOGNESI MZ. 02 LT. 25",ref:"A ESPALDAS DE LA POLLERIA PICO DORADO Y A MEDIA CDRA. DE LA AV SANTA BARBARA",a:1},
  {l:"AEROPUERTO CUSCO",d:"CUSCO",p:"CUSCO",t:"CUSCO",dir:"AEROPUERTO INTERNACIONAL ALEJANDRO VELASCO ASTETE"},
  {l:"AV ANTONIO LORENA",d:"CUSCO",p:"CUSCO",t:"SANTIAGO",dir:"Prolongación Av. Antonio Lorena # 140 - Santiago",ref:"al frente del cementerio Almudena",a:1},
  {l:"AV PACHACUTEC",d:"CUSCO",p:"CUSCO",t:"WANCHAQ",dir:"AV. PACHACUTEC 429 - WANCHAQ",ref:"A 100 MTRS. DE LA PISCINA WANCHAQ",a:1},
  {l:"CACHIMAYO - SAN SEBASTIAN",d:"CUSCO",p:"CUSCO",t:"SAN SEBASTIAN",dir:"URB. CACHIMAYO A-37 AV. LA CULTURA – SAN SEBASTIAN – CUSCO",ref:"ENTRE PARADERO ENACO Y PARQUE CACHIMAYO, A 2 CUADRA DE LA UNIVERSIDAD ANDINA",a:1},
  {l:"CUSCO CO VIA EVITAMIENTO",d:"CUSCO",p:"CUSCO",t:"SAN SEBASTIAN",dir:"AV. EVITAMIENTO S/N UPS CHACAHUAYCO",ref:"VÍA EVITAMIENTO EN EL PARADERO HORACIO",a:1},
  {l:"CUSCO PARQUE INDUSTRIAL",d:"CUSCO",p:"CUSCO",t:"WANCHAQ",dir:"AV. LAS AMERICAS MZ. E LT. 20",ref:"AL FRENTE DE TALLERES PFURO, AL FRENTE DE MEDERERA URPI, PARALELA A LA AV VIA EXPRESA",a:1},
  {l:"HUANCARO",d:"CUSCO",p:"CUSCO",t:"SANTIAGO",dir:"URB. VILLA UNION F-1-B HUANCARO",ref:"FRENTE A LA IGLESIA DE LOS MORMONES/ A UNA CDRA. DEL MERCADO HUANCARO",a:1},
  {l:"SAN JERONIMO",d:"CUSCO",p:"CUSCO",t:"SAN JERONIMO",dir:"CALLE CIRO ALEGRÍA 226 - 224",ref:"UNA CUADRA ANTES DEL PARADERO PENAL EN EL CARRIL DE BAJADA",a:1},
  {l:"TICA TICA",d:"CUSCO",p:"CUSCO",t:"CUSCO",dir:"ARCO TICATICA PUSTIPATA",ref:"EN LA AV. PRINCIPAL A 3 CDRAS. DEL MERCADO TICA TICA",a:1},
  {l:"URB. BANCOPATA AV. INDUSTRIAL",d:"CUSCO",p:"CUSCO",t:"SANTIAGO",dir:"AV. INDUSTRIAL URB. BANCOPATA J-20",ref:"A 2 CDRAS. DEL OVALO PACHACUTEC, FRENTE A LA EMPRESA COCA COLA",a:1},
  {l:"VELASCO ASTETE",d:"CUSCO",p:"CUSCO",t:"WANCHAQ",dir:"VELASCO ASTETE D3 - WANCHAQ",ref:"A 2 CDRAS. DEL AEREOPUERTO",a:1},
  {l:"VIA EXPRESA SUR",d:"CUSCO",p:"CUSCO",t:"SAN SEBASTIAN",dir:"URB. TUPAC AMARU B-1-2 SAN SEBASTIAN – CUSCO",ref:"TERMINANDO LA VIA EXPRESA ZONA SUR",a:1},
  {l:"ESPINAR",d:"CUSCO",p:"ESPINAR",t:"YAURI ( ESPINAR )",dir:"CALLE SAN JOSE N° 703 BARRIO PROGRESO",ref:"A MEDIA CDRA. DEL GRIFO SAN JOSE / A MEDIA CDRA. DE LA AV. TINTAYA",a:1},
  {l:"PICHARI",d:"CUSCO",p:"LA CONVENCION",t:"PICHARI",dir:"ASOC. GRAL. JUAN VELASCO A. MZ. B LT. 2",ref:"AL COSTADO DE TECHO PROPIO"},
  {l:"QUILLABAMBA",d:"CUSCO",p:"LA CONVENCION",t:"SANTA ANA",dir:"JR. PUNO LT. 10 Y 11 MZ. G URB. SANTA ANA",ref:"A MEDIA CDRA.l DEL ESTADIO MUNICIPAL DE QUILLABAMBA",a:1},
  {l:"OCONGATE",d:"CUSCO",p:"QUISPICANCHI",t:"OCONGATE",dir:"SECT. MAYO UCJO S/N",ref:"A LA ESPALDA DEL TERMINAL DE BUSES DE OCONGATE / A ORILLAS DE LA CARRETA A MAZUKO",a:1},
  {l:"OROPESA",d:"CUSCO",p:"QUISPICANCHI",t:"OROPESA",dir:"SEC. CHIMPAPAMPA APV. JOSE CCARLOS MAREATEGUI S/N",ref:"A UNA CDRA. DE LA CARRETA A URCOS / A UNA CDRA. DE LA PANIFICADORA CACHITO AMARILLO",a:1},
  {l:"URCOS",d:"CUSCO",p:"QUISPICANCHI",t:"URCOS",dir:"MAYUPATA S/N PAUCARBAMBA",ref:"AL FRENDE DEL ESTADIO MUNICIPAL DE URCOS / AL FRENTE DEL TERMINAL TERRESTRE DE URCOS",a:1},
  {l:"CHINCHERO",d:"CUSCO",p:"URUBAMBA",t:"CHINCHERO",dir:"AV. MATEO PUMACAHUA S/N",ref:"AL COSTADO DE LA CAJA CUSCO / EN LA MISMA CARRETERA A URUBAMBA",a:1},
  {l:"CUSCO URUBAMBA",d:"CUSCO",p:"URUBAMBA",t:"URUBAMBA",dir:"LT. E-3 FRACCIÓN -1",ref:"A UNA CDRA. DE LA CARRETERA A OLLANTAYTAMBO / A MEDIA CDRA. DEL PARQUE TERESITA",a:1},
  {l:"HUANCAVELICA",d:"HUANCAVELICA",p:"HUANCAVELICA",t:"HUANCAVELICA",dir:"AV. UNIVERSITARIA 1003 - HUANCAVELICA",ref:"A 1 CDRA. DE LA ESCUELA SANTA ANA Y A 3 CDRAS. DEL PUENTE DEL EJÉRCITO (BARRIO SANTA ANA)",a:1},
  {l:"HUANCAVELICA JR. OROPEZA (POR DEFINIR)",d:"HUANCAVELICA",p:"HUANCAVELICA",t:"HUANCAVELICA",dir:"AV. ANDRÉS A. CÁCERES N° 198",ref:"A MEDIA CDRA. DE LA PLAZOLETA \"TUPAC AMARU\" Y EN LA ESQUINA CON CALLE OROPEZA (BARRIO"},
  {l:"AMBO",d:"HUANUCO",p:"AMBO",t:"AMBO",dir:"AV. LAS AMERICAS 501",ref:"AL FRENTE DEL COLEGIO JUAN JOSÉ CRESPO Y CASTILLO",a:1},
  {l:"AMARILIS CO",d:"HUANUCO",p:"HUANUCO",t:"AMARILIS",dir:"JR. LOS PINOS LOTE 3 -D2 URB LOS PINOS - AMARILIS - HUÁNUC",ref:"A LA ESPALDA DE TOYOTA HUÁNUCO",a:1},
  {l:"JR AGUILAR",d:"HUANUCO",p:"HUANUCO",t:"HUANUCO",dir:"Jr. Aguilar N° 872 - Huánuco",a:1},
  {l:"AUCAYACU",d:"HUANUCO",p:"LEONCIO PRADO",t:"JOSE CRESPO Y CASTIL",dir:"JR. CHICLAYO 247 0C-02 CENT AUCAYU",ref:"ATRÁS DEL ESTADIO MUNICIPAL",a:1},
  {l:"TINGO MARIA CO BUENOS AIRES",d:"HUANUCO",p:"LEONCIO PRADO",t:"RUPA RUPA",dir:"CALLE ROSARIO CENTRAL",ref:"SEGUNDA ENTRADA DE BUENOS AIRES, EN LA MISMA ESQUINA",a:1},
  {l:"TINGO MARÍA - LEONCIO PRADO",d:"HUANUCO",p:"LEONCIO PRADO",t:"RUPA RUPA",dir:"AV. TITO JAIME 914",ref:"A DOS CDRAS. DE LA PLAZA DE ARMAS LEONCIO PARDO",a:1},
  {l:"CALLE LOS ANGELES",d:"ICA",p:"CHINCHA",t:"CHINCHA ALTA",dir:"CALLE LOS ÁNGELES N° CASA 217 01 - A SIN BARRIIO CERCADO",ref:"A 2 CDRAS. DE LA PLAZA DE ARMAS DE CHNCHA PASANDO ELECTRODUNAS",a:1},
  {l:"CHINCHA PUEBLO NUEVO",d:"ICA",p:"CHINCHA",t:"PUEBLO NUEVO",dir:"AA. HH. LOS ALAMOS",ref:"A 2 CDRAS. DE LA POSTA LOS ÁLAMOS",a:1},
  {l:"PROLONG LUIS MASSARO",d:"ICA",p:"CHINCHA",t:"CHINCHA ALTA",dir:"PROLONGACION LUIS MASSARO N°247 - CHINCHA ALTA",a:1},
  {l:"SUNAMPE  CO",d:"ICA",p:"CHINCHA",t:"SUNAMPE",dir:"CARR. PANAMERICANA SUR NRO. 198 -B",ref:"ANTIGUA PANAMERICANA SUR FRENTE A LA ENTRADA DE GROCIO PRADO",a:1},
  {l:"ICA AV. JJ ELIAS",d:"ICA",p:"ICA",t:"ICA",dir:"MANZANA B",ref:"CRUCE DE AV. CUTERVO CON AV. J.J ELIAS",a:1},
  {l:"ICA SAN JOAQUIN",d:"ICA",p:"ICA",t:"ICA",dir:"Pasaje Grau N° 101 San Joaquin - ICA REFERENCIA : A 1 cdra",ref:"A 1 cdra de Petro Peru",a:1},
  {l:"ICA SANTIAGO",d:"ICA",p:"ICA",t:"SANTIAGO",dir:"CENTRO POBLADO SANTIAGO MZ. E",ref:"FRENTE A LA COMISARIA DE SANTIAGO",a:1},
  {l:"ICA SUBTANJALLA CO",d:"ICA",p:"ICA",t:"SUBTANJALLA",dir:"C.P - SECTOR MACACONA /PREDIO PARCELA 214 LOTE 2",ref:"PANAMERICANA SUR FRENTE A LA ENTRADA DEL ARRABAL",a:1},
  {l:"ICA URB. MANZANILLA",d:"ICA",p:"ICA",t:"ICA",dir:"AV. MANUEL SANTANA CHIRI N°359 A1 – ICA",ref:"CRUCE CON CALLE BALTAZAR CARAVEDO",a:1},
  {l:"LA TINGUIÑA",d:"ICA",p:"ICA",t:"LA TINGUINA",dir:"CALLE FRANCISCO SALES SOTELO N° 298 SUB LOTE 3",ref:"CRUCE DE LA AV.FRNCISCO SALES SOTELO Y AV. JOSE CARLOS MARIATEGUI",a:1},
  {l:"PARCONA",d:"ICA",p:"ICA",t:"PARCONA",dir:"CP. DE PARCONA -CERCADO (PRIMERA ETAPA) MZ. B LOTE 16 PARC",ref:"AV. 18 DE FEBRERO Y CRUCE DE AV. NATIVIDAD PACO",a:1},
  {l:"SALAS ICA",d:"ICA",p:"ICA",t:"SALAS",dir:"SUB LOTE 01 ZONA PANAMERICANA SUR KM. 293.350",ref:"FRENTE AL ESTADIO DE SALAS GUADALUPE",a:1},
  {l:"AV CIRCUNVALACION NAZCA",d:"ICA",p:"NAZCA",t:"NAZCA",dir:"EN LA ESQUINA DE LA AV. CIRCUNVALACIÓN CON CALLE S/N",ref:"AL LADO DE LA IEP JEAN PIAGET",a:1},
  {l:"EL INGENIO",d:"ICA",p:"NAZCA",t:"EL INGENIO",dir:"AV. PRINCIPAL TULIN 204",ref:"FREMTE A A LA PLAZA DE TULIN"},
  {l:"SAN JUAN DE MARCONA",d:"ICA",p:"NAZCA",t:"MARCONA",dir:"A. H. SAN MARTÍN DE PORRES E-28 SAN JUAN DE MARCONA - NAZC",ref:"ENTRE EL HOTEL SAN MARTIN Y EL MINIMARKET LANA",a:1},
  {l:"VISTA ALEGRE CO",d:"ICA",p:"NAZCA",t:"VISTA ALEGRE",dir:"CARRETERA PANAMERICANA SUR N\\u00b0 906",ref:"FRENTE AL AEROPUERTO DE VISTA ALEGRE",a:1},
  {l:"AV ABRAHAM VALDELOMAR CO",d:"ICA",p:"PISCO",t:"PISCO",dir:"AV. ABRAHAM VALDELOMAR NRO. PUERTA 965 PISCO - PISCO - ICA",ref:"A UNA CDRA. POR LA POSTA SAN MARTIN",a:1},
  {l:"LA VILLA  CRUCE PISCO",d:"ICA",p:"PISCO",t:"PISCO",dir:"C. P. OBLACION VILLA LOS ANGELES MZ.A LT 13 B LA VILLA PIS",ref:"A 100 METROS CON DIRECCIÓN AL SUR DEDL CRUCE PANAMERICANA ANTIGUA C/N AV. FERMÍN TANGÜIS",a:1},
  {l:"SAN CLEMENTE",d:"ICA",p:"PISCO",t:"SAN CLEMENTE",dir:"AV. LOS LIBERTADORES GRUPO NÚMERO 1 MZ",ref:"LIBERTADORES SEXTA CUADRA,FRENTE DEL GRIFO SANTA ROSA",a:1},
  {l:"LA MERCED",d:"JUNIN",p:"CHANCHAMAYO",t:"LA MERCED",dir:"AV. PERU 931 SECTOR PAMPA DEL CARMEN",ref:"FRENTE A LA COOPERATIVA CHANCHAMAYO",a:1},
  {l:"PERENE",d:"JUNIN",p:"CHANCHAMAYO",t:"PERENE",dir:"AV. MARGINAL S/N AA.VV SAN JACINTO - PERENE - CHANCHAMAYO",ref:"ANTES DEL ULTIMO ROMPEMUELLE DE SAN JACINTO",a:1},
  {l:"PICHANAKI",d:"JUNIN",p:"CHANCHAMAYO",t:"BAJO PICHANAQUI",dir:"AV. VENUS LT. 20 CIUDAD SATÉLITE - REF. ( A 1 CUADRA Y MED",ref:"( A 1 CUADRA Y MEDIA DEL PARQUE DE SATÉLITE)",a:1},
  {l:"SAN RAMÓN",d:"JUNIN",p:"CHANCHAMAYO",t:"SAN RAMON",dir:"JR. UCAYALI 102 - SAN RAMÓN",ref:"FRENTE A LA CAJA HUANCAYO Y EL PARQUE EL AVIÓN",a:1},
  {l:"CHUPACA",d:"JUNIN",p:"CHUPACA",t:"CHUPACA",dir:"JR. RAMON CASTILLA 201",ref:"A UNA CDRA. DE LA PLAZA PRINCIPAL DE CHUPACA",a:1},
  {l:"CONCEPCION",d:"JUNIN",p:"CONCEPCION",t:"CONCEPCION",dir:"CARRETERA CENTRAL LT. 7 - MZ. E5",ref:"ESQUINA CON TUPAC AMARU",a:1},
  {l:"AV CIRCUNVALACIÓN CRUCE CON MARIATEGUI",d:"JUNIN",p:"HUANCAYO",t:"EL TAMBO",dir:"AV. CIRCUNVALACIÓN 480 T-1",ref:"ESQUINA CON PROLONGACIÓN MARIATEGUI",a:1},
  {l:"AV MARISCAL CASTILLA CO PARQUE INDUSTRIAL",d:"JUNIN",p:"HUANCAYO",t:"EL TAMBO",dir:"AV MARISCAL CASTILLA 2769 RefERENCIA : Frente al colegio A",ref:"Frente al colegio Andres bello",a:1},
  {l:"CHILCA HUANCAYO",d:"JUNIN",p:"HUANCAYO",t:"CHILCA",dir:"JR. 28 DE JULIO N° 935",ref:"ESQUINA 28 DE JULIO Y SANTOS CHOCANO",a:1},
  {l:"CHILCA LEONCIO PRADO",d:"JUNIN",p:"HUANCAYO",t:"CHILCA",dir:"JR. LEONICO PRADO 656",ref:"ESQUINA CON JIRON JOSE OLAYA",a:1},
  {l:"CIUDAD UNIVERSITARIA",d:"JUNIN",p:"HUANCAYO",t:"EL TAMBO",dir:"Jr Tarma Nro. 37 - 24",ref:"AL COSTADO DE LA FACULTaD DE INGENIERÍA METALÚRGICA UNCP",a:1},
  {l:"HUANCAYO JR. ICA",d:"JUNIN",p:"HUANCAYO",t:"HUANCAYO",dir:"JR. ICA Nº 1143 - HUANCAYO",ref:"ENTRE EL JR. ICA Y EL JR. TACNA",a:1},
  {l:"PILCOMAYO",d:"JUNIN",p:"HUANCAYO",t:"PILCOMAYO",dir:"PLAZA INDEPENDENCIA 131",ref:"PLAZA PRINCIPAL DE PILCOMAYO",a:1},
  {l:"PIO  PATA",d:"JUNIN",p:"HUANCAYO",t:"EL TAMBO",dir:"AV. HUANCAVELICA 1201",ref:"ESQUINA CON EL JR. LA VICTORIA",a:1},
  {l:"SAN AGUSTIN DE CAJAS",d:"JUNIN",p:"HUANCAYO",t:"SAN AGUSTIN",dir:"CARRETERA CENTRAL KM 7.5 S/N SAN AGUSTIN – HUANCAYO – JUNÍ",ref:"FRENTE A LA ENVASADORA SOLGAS",a:1},
  {l:"SAN CARLOS HUANCAYO",d:"JUNIN",p:"HUANCAYO",t:"HUANCAYO",dir:"PJ. SAN FERNANDO 209 HUANCAYO - HUANCAYO - JUNIN",ref:"ESQUINA DEL JR. SAN FERNANDO Y MÁRTIRES DEL PERIODISMO",a:1},
  {l:"SAPALLANGA HUANCAYO (POR DEFINIR)",d:"JUNIN",p:"HUANCAYO",t:"SAPALLANGA",dir:"CA. CORONEL CISNEROS 598",ref:"ESQUINA CON AV. MARISCAL CACERES"},
  {l:"TERMINAL DE BUS",d:"JUNIN",p:"HUANCAYO",t:"HUANCAYO",dir:"Av. Evitamiento s/n - counter N°13"},
  {l:"TERMINAL LOS ANDES",d:"JUNIN",p:"HUANCAYO",t:"HUANCAYO",dir:"AV. FERROCARRIL S/N - HUANCAYO - COUNTER N° 14",ref:"TERMINAL TERRESTRE LOS ANDES, FRENTE AL OPEN PLAZA",a:1},
  {l:"JAUJA",d:"JUNIN",p:"JAUJA",t:"JAUJA",dir:"Jr. ESTANISLAO MARQUEZ 286",ref:"ESQUINA CON JR. 4 DE ENERO",a:1},
  {l:"TERMINAL JAUJA",d:"JUNIN",p:"JAUJA",t:"JAUJA",dir:"JR.LUIS BARDALES S/N",ref:"TERMINAL TERRESTRE HATUN XAUXA",a:1},
  {l:"MAZAMARI",d:"JUNIN",p:"SATIPO",t:"MAZAMARI",dir:"JR. JORGE CHAVEZ NRO 144 LT. 8A JUNÍN - SATIPO– MAZAMARI",ref:"CERCA A LA VÍA PRINCIPAL, AL COSTADO DEL HOSPEDAJE LUJÁN 1ER PISO",a:1},
  {l:"PANGOA",d:"JUNIN",p:"SATIPO",t:"PANGOA",dir:"AV. MARGINAL S/N NÚMERO VILLA CHAVINI PANGOA - SATIPO - JU",ref:"AL COSTADO DE LA TIENDA HONDA INVERSIONES ARAUCO SAN MARTÍN DE PANGOA",a:1},
  {l:"SATIPO",d:"JUNIN",p:"SATIPO",t:"SATIPO",dir:"JR. FRANCISCO IRAZOLA 1077 - JUNÍN",ref:"FÁBRICA LA SATIPEÑA",a:1},
  {l:"TARMA",d:"JUNIN",p:"TARMA",t:"TARMA",dir:"JR. AMAZONAS NRO. 1164 TARMA - JUNÍN",ref:"ENTRE JR. AMAZONAS CON AV. VIENRICH",a:1},
  {l:"LA OROYA",d:"JUNIN",p:"YAULI",t:"LA OROYA",dir:"AV. ARÉVALO S/N (CARRETERA CENTRAL) - ANEXO EL TAMBO - SAN",a:1},
  {l:"CASA GRANDE",d:"LA LIBERTAD",p:"ASCOPE",t:"CASA GRANDE",dir:"CALLE LUIS SÁNCHEZ N° 152 SECTOR PARTE ALTA. CASA GRANDE -",ref:"CRUCE CON AV. ESTADIO",a:1},
  {l:"PAIJAN",d:"LA LIBERTAD",p:"ASCOPE",t:"PAIJAN",dir:"AV. PANAMERICANA NRO. 2321 LA LIBERTAD - ASCOPE - PAIJAN",ref:"A 1 CDRA. DEL ESTADIO MUNICIPAL DE PAIJÁN",a:1},
  {l:"CHEPEN",d:"LA LIBERTAD",p:"CHEPEN",t:"CHEPEN",dir:"PROLONGACION EZEQUIEL GONZALES CACEDA 193 - SEC. CHEPEN",a:1},
  {l:"PACANGUILLA",d:"LA LIBERTAD",p:"CHEPEN",t:"PACANGA",dir:"CARRETERA PANAMERICANA # 835 - URB. PACANGUILLA - DISTRITO",ref:"EN LA MISMA PANAMERICANA",a:1},
  {l:"OTUZCO",d:"LA LIBERTAD",p:"OTUZCO",t:"OTUZCO",dir:"AV. ALFREDO GUTIÉRREZ N° 120 - Otuzco - Otuzco - La Libert",a:1},
  {l:"CIUDAD DE DIOS",d:"LA LIBERTAD",p:"PACASMAYO",t:"GUADALUPE",dir:"MZ. A LT. 01 CPM CIUDAD DE DIOS - SEC. LOS ÁNGELES – GUADA",ref:"AL COSTADO DEL MOLINO SAMÁN Y A DOS CUADRAS DEL CRUCE A CAJAMARCA",a:1},
  {l:"GUADALUPE LA LIBERTAD",d:"LA LIBERTAD",p:"PACASMAYO",t:"GUADALUPE",dir:"AV. NILLA CERRUTY N° 299 - GUADALUPE – PACASMAYO – LA LIBE",ref:"AL COSTADO DEL GRIFO REPSOL - NEOTECH",a:1},
  {l:"PACASMAYO CENTRO",d:"LA LIBERTAD",p:"PACASMAYO",t:"PACASMAYO",dir:"AV. GONZALO UGAZ SALCEDO S/N - PACASMAYO - LA LIBERTAD",ref:"AL COSTADO DEL ESTADIO MUNICIPAL DE PACASMAYO / A MEDIA CDRA. DEL SUPERMERCADO TOTTUS",a:1},
  {l:"PACASMAYO LAS PALMERAS",d:"LA LIBERTAD",p:"PACASMAYO",t:"PACASMAYO",dir:"CTRA. PANAMERICANA NORTE N° MZ. P LT. 4A - A.H. LAS PALMER",ref:"ENTRE AV. SUCRE Y AV. LEONCIO PRADO",a:1},
  {l:"SAN PEDRO DE LLOC",d:"LA LIBERTAD",p:"PACASMAYO",t:"SAN PEDRO DE LLOC",dir:"AV. VÍA DE EVITAMIENTO N° 407",ref:"A MEDIA CDRA. DE LA CALLE LIBERTAD/ A MEDIA CDRA. DEL PARADERO DE LA VIA DE EVITAMIENTO",a:1},
  {l:"HUAMACHUCO",d:"LA LIBERTAD",p:"SANCHEZ CARRION",t:"HUAMACHUCO",dir:"JR. SIMON BOLIVAR 763",ref:"ENTRE JR. INDEPENDECIA Y JR. ALFONSO UGARTE",a:1},
  {l:"ALTO TRUJILLO",d:"LA LIBERTAD",p:"TRUJILLO",t:"EL PORVENIR",dir:"AV. PROLONGACIÓN 12 DE NOVIEMBRE",ref:"A MEDIA CDRA. DE LA COMISARÍA ALTO TRUJILLO",a:1},
  {l:"ATAHUALPA",d:"LA LIBERTAD",p:"TRUJILLO",t:"TRUJILLO",dir:"CALLE ATAHUALPA 481 – TRUJILLO – LA LIBERTAD",ref:"A 1/2 CDRA DE LA AV LOS INCAS",a:1},
  {l:"AV HERMANOS ANGULO",d:"LA LIBERTAD",p:"TRUJILLO",t:"EL PORVENIR",dir:"AV. HERMANOS ANGULO 628",ref:"A ESPALDAS DE LA MUNICIPALIDAD EL PORVENIR",a:1},
  {l:"AV HNOS UCEDA - AMERICA NORTE",d:"LA LIBERTAD",p:"TRUJILLO",t:"TRUJILLO",dir:"AV. HERMANOS UCEDA MEZA N° 269 URB MIRAFLORES II ETAPA - T",ref:"A UNA CDRA. DE AV. AMERICA NORTE. / ENTRE AV. MIRAFLORES Y AV. SALVADOR LARA",a:1},
  {l:"AV LARCO",d:"LA LIBERTAD",p:"TRUJILLO",t:"VICTOR LARCO HERRERA",dir:"AV. LARCO 865",ref:"MZ X LT 28 CUI SAN ANDRES V ETAPA TERCER SECTOR Y FRENTE AL COLEGIO JESUS MARIA"},
  {l:"AV TAHUANTINSUYO",d:"LA LIBERTAD",p:"TRUJILLO",t:"LA ESPERANZA",dir:"AV. TAHUANTINSUYO N° 739",ref:"DIAGONAL A GRIFO EL AMIGO. / ENTRE PASAJE SANTA ANA Y AV. LOS LAURELES",a:1},
  {l:"AV. 12 DE NOVIEMBRE (POR DEFINIR)",d:"LA LIBERTAD",p:"TRUJILLO",t:"EL PORVENIR",dir:"AV. 12 DE NOVIEMBRE M. W LOTE 19 MZ. 3A",ref:"AL FRENTE DEL COMPLETO DEPORTIVO JOSÉ CAIPO"},
  {l:"AV. LAS MAGNOLIAS",d:"LA LIBERTAD",p:"TRUJILLO",t:"EL PORVENIR",dir:"AV. LAS MAGNOLIAS MZ. 25 LT. 2A NUEVO PORVENIR",ref:"A UNA CDRA. DEL PODER JUDICIAL CISAJ SEDE EL PORVENIR",a:1},
  {l:"CALLE LIVERPOOL",d:"LA LIBERTAD",p:"TRUJILLO",t:"TRUJILLO",dir:"Calle LiverpoOl N° 329 / Urb. Santa Isabel - Trujillo. ref",ref:"a una cuadra antes de la Iglesia de Mansiche",a:1},
  {l:"CALLE SANTA CRUZ - AMERICA SUR",d:"LA LIBERTAD",p:"TRUJILLO",t:"TRUJILLO",dir:"CALLE SANTA CRUZ N° 389 CHICAGO - TRUJILLO - LA LIBERTAD",ref:"A MEDIA CDRA. DE LA AV. AMERICA SUR/A MEDIA CUADRA DEL ESTADIO CHAN CHAN",a:1},
  {l:"EL MILAGRO",d:"LA LIBERTAD",p:"TRUJILLO",t:"HUANCHACO",dir:"AV. INDUSTRIAL MZ 23 LT. 13 SECTOR II – EL MILAGRO",ref:"A 2 CDRAS. DE LA PLAZA DE ARMAS DE EL MILAGRO",a:1},
  {l:"JR. CAHUIDE",d:"LA LIBERTAD",p:"TRUJILLO",t:"EL PORVENIR",dir:"JR. CAHUIDE N° 342 AA.HH LA MERCED - EL PORVENIR - TRUJILL",ref:"A UNA CDRA. DEL ARCO DEL PORVENIR / A UNA CDRA. DE LA PARROQUIA EL BUEN PASTOR",a:1},
  {l:"MOCHE",d:"LA LIBERTAD",p:"TRUJILLO",t:"MOCHE",dir:"AV. LA MARINA LOTE 25 - B – MOCHE – TRUJILLO - LA LIBERTAD",ref:"A MEDIA CDRA DE LA COMISARÍA DE MOCHE",a:1},
  {l:"OVALO HUANCHACO CO",d:"LA LIBERTAD",p:"TRUJILLO",t:"HUANCHACO",dir:"CARRETERA VIA DE EVITAMIENTO 576.2 HUANCHAQUITO ALTO - TRU",ref:"A 1 CDRA. DE OVALO HUANCHACO / AL COSTADO DE CONDOMINIO LAS BRISAS",a:1},
  {l:"OVALO PAPAL",d:"LA LIBERTAD",p:"TRUJILLO",t:"TRUJILLO",dir:"URB. VISTA HERMOSA MZ. F LT. 11 PISO °1 TRUJILLO - TRUJILL",ref:"A ESPALDAS DEL METRO DEL OVALO PAPAL",a:1},
  {l:"TRUJILLO LA PERLA",d:"LA LIBERTAD",p:"TRUJILLO",t:"TRUJILLO",dir:"AV. LA PERLA MZ. E LOTE 05 URB. INGENIERIA – TRUJILLO – LA",ref:"A 1 cDRA. DEL COLEGIO BRUNING",a:1},
  {l:"WICHANZAO",d:"LA LIBERTAD",p:"TRUJILLO",t:"LA ESPERANZA",dir:"MZ. 1 LT. 23 AA.HH WICHANZAO – LA ESPERANZA – TRUJILLO – L",ref:"AL COSTADO DEL ALMACÉN SUNAT.",a:1},
  {l:"aperopuerto TRUJILLO",d:"LA LIBERTAD",p:"TRUJILLO",t:"TRUJILLO",dir:"Aeropuerto Internacional Capitán FAP Carlos Martinez de Pi"},
  {l:"CHAO",d:"LA LIBERTAD",p:"VIRU",t:"CHAO",dir:"AV. VICTOR RAUL HAYA DE LA TORRE 575 CHAO - VIRU",ref:"A MEDIA CDRA. DE LA COMISARÍA DE CHAO",a:1},
  {l:"PUENTE VIRU",d:"LA LIBERTAD",p:"VIRU",t:"VIRU",dir:"PANAMERICANA NORTE N° 933 PUENTE VIRÚ - VIRÚ - LA LIBERTAD",ref:"a MEDIA CDRA. DEL GRIFO ZONA ETNA/MEDIA CDRA. DEL SEMAFORO ZONA ETNA",a:1},
  {l:"VIRU CENTRO",d:"LA LIBERTAD",p:"VIRU",t:"VIRU",dir:"CALLE PUNO N° 125 - MZ. 32 LT. 7A - VIRÚ - LA LIBERTAD",ref:"A MEDIA CDRA. DEL CRUCE DE LA AV. VIRU CON LA CALLE JORGE CHAVEZ",a:1},
  {l:"AEROPUERTOCHICLAYO",d:"LAMBAYEQUE",p:"CHICLAYO",t:"CHICLAYO",dir:"Aeropuerto Internacional Capitán FAP José Abelardo Quiñone"},
  {l:"AV  BALTA CDRA. 36",d:"LAMBAYEQUE",p:"CHICLAYO",t:"JOSE LEONARDO ORTIZ",dir:"AV. JOSE BALTA N° 3653 C.P.M. PRIMERO DE MAYO JOSE LEONARD",ref:"ENTRE LA AV. BALTA Y NÉSTOR BARSALLO / A 2 CUADRAS DE LA AV. CHICLAYO",a:1},
  {l:"AV LAS AMERICAS",d:"LAMBAYEQUE",p:"CHICLAYO",t:"CHICLAYO",dir:"AV. LAS AMÉRICAS LT. 42 MZ. D",ref:"A MEDIA CDRA. ENTRE LA AV. COLECTORA Y AV. LAS AMERICAS Y A MEDIA CDRA. DEL GRIFO SR. DE",a:1},
  {l:"AV VICTOR R. HAYA CO",d:"LAMBAYEQUE",p:"CHICLAYO",t:"LA VICTORIA",dir:"av. VÍCTOR RAUL HAYA DE LA TORRE 2470 La Victoria - Chicla",ref:"ENTRE LA VIA EVITAMIENTO Y PANAMERICANA",a:1},
  {l:"CALLE TACNA",d:"LAMBAYEQUE",p:"CHICLAYO",t:"CHICLAYO",dir:"CALLE. TACNA N° 1095 -CHICLAYO- CHICLAYO - LAMBAYEQUE",ref:"INTERSECCIÓN CON AV. JOSE QUIÑONES / A ESPALDAS DEL SUPERMERCADO MAKRO CHICLAYO",a:1},
  {l:"CALLE TAHUANTINSUYO",d:"LAMBAYEQUE",p:"CHICLAYO",t:"JOSE LEONARDO ORTIZ",dir:"CALLE TAHUANTINSUYO 995 - URB. SAN LORENZO - JOSE LEONARDO",ref:"ENTRE LA CDRA. 2 DE AV. AMÉRICA Y LA CALLE TAHUANTINSUYO",a:1},
  {l:"CHONGOYAPE",d:"LAMBAYEQUE",p:"CHICLAYO",t:"CHONGOYAPE",dir:"AV. ATAHUALPA N° 1200 - CHONGOYAPE - CHICLAYO - LAMBAYEQUE",ref:"INTERSECCION CON CALLE IQUITOS / A 2 CDRAS. DE LA INTERSECCION CON LA AV. CHICLAYO",a:1},
  {l:"MIRAFLORES CHICLAYO",d:"LAMBAYEQUE",p:"CHICLAYO",t:"CHICLAYO",dir:"AV. PANAMERICANA 975 PP JJ LUIS ALBERTO SANCHEZ",ref:"A MEDIA CDRA. DEL OVALO SEÑOR DE SIPAN / AL FRENTE DE DERCO CENTER",a:1},
  {l:"MONSEFU",d:"LAMBAYEQUE",p:"CHICLAYO",t:"MONSEFU",dir:"AV. VENEZUELA N° 221",ref:"REF 01: A MEDIA CDRA. DE LA CALLE DIEGO FERRE Y A CDRA. Y MEDIA DEL PARQUE ARTESANAL DE",a:1},
  {l:"PATAPO",d:"LAMBAYEQUE",p:"CHICLAYO",t:"PATAPO",dir:"AV. CHONGOYAPE N° S/N SECTOR CERRO MIRADOR",ref:"A UNA CDRA. Y MEDIA DE LA INTERSECCIÓN CON AV TRAPICHE",a:1},
  {l:"PIMENTEL",d:"LAMBAYEQUE",p:"CHICLAYO",t:"PIMENTEL",dir:"CALLE MIGUEL GRAU MZ B LOTE 3 - PIMENTEL - CHICLAYO - LAMB",ref:"AL COSTADO DE LA COMISARIA DE PIMENTEL",a:1},
  {l:"POMALCA",d:"LAMBAYEQUE",p:"CHICLAYO",t:"POMALCA",dir:"CALLE 25 MZ. I LT. 6 SECT. 6 SAN JUAN",ref:"A UNA CDRA. Y MEDIA DE LA INTERSECCIÓN CON AV. SAN MARTIN/ AL FRENTE DE LA IGLESIA MORMON",a:1},
  {l:"REQUE",d:"LAMBAYEQUE",p:"CHICLAYO",t:"REQUE",dir:"AV. MARISCAL RAMON CASTILLA MZ. 4 LOTE 14",ref:"A MEDIA CDRA. DE LA INTERSECCION CON CALLE SAN MARTIN",a:1},
  {l:"TUMAN",d:"LAMBAYEQUE",p:"CHICLAYO",t:"TUMAN",dir:"AV. CHOTA N° 288 SECTOR ACAPULCO",ref:"AL COSTADO DEL RESTAURANT MANOS CHOTANAS",a:1},
  {l:"FERREÑAFE",d:"LAMBAYEQUE",p:"FERRENAFE",t:"FERRENAFE",dir:"AV. ANDRÉS A. CÁCERES N°550A",ref:"AL COSTADO DEL GRIFO PRIMAX",a:1},
  {l:"JAYANCA",d:"LAMBAYEQUE",p:"LAMBAYEQUE",t:"JAYANCA",dir:"CALLE DIEGO FERRE N°1321 - JAYANCA - LAMBAYEQUE",ref:"AL FRENTE DEL CENTRO DE SALUD DE JAYANCA / A MEDIA CDRA. DEL GRIFO ASIA",a:1},
  {l:"LAMBAYEQUE CENTRO",d:"LAMBAYEQUE",p:"LAMBAYEQUE",t:"LAMBAYEQUE",dir:"AV. FEDERICO VILLARREAL N° 491",ref:"A MEDIA CDRA. DE LA INTERSECCION DE LA AV. FEDERICO VILLARREAL CON CALLE EMILIANO NIÑO",a:1},
  {l:"LAMBAYEQUE PANAMERICANA",d:"LAMBAYEQUE",p:"LAMBAYEQUE",t:"LAMBAYEQUE",dir:"CALLE PARAGUAY MZ. D LT 2A UNIDAD VECINAL INDOAMÉRICA - LA",ref:"AL COSTADO DE LA FÁBRICA DE KINKONES BRUNING / A 01 CUADRA DEL PUENTE LAMBAYEQUE",a:1},
  {l:"MORROPE",d:"LAMBAYEQUE",p:"LAMBAYEQUE",t:"MORROPE",dir:"CALLE TAHUANTINSUYO N° 821",ref:"FRENTE AL PARQUE INFANTIL DE MORROPE",a:1},
  {l:"MOTUPE",d:"LAMBAYEQUE",p:"LAMBAYEQUE",t:"MOTUPE",dir:"AV. EL MAESTRO N° 447 - MOTUPE - LAMBAYEQUE- LAMBAYEQUE",ref:"EN LA CARRETERA FERNANDO BELAUNDE TERRY (PANAMERICANA NORTE) / AL FRENTE DEL GRIFO AVA",a:1},
  {l:"OLMOS",d:"LAMBAYEQUE",p:"LAMBAYEQUE",t:"OLMOS",dir:"AV. AUGUSTO B. LEGUÍA MZ. 87 LT. 32 - OLMOS - LAMBAYEQUE",ref:"AL FRENTE DE LA COMISARIA DE OLMOS",a:1},
  {l:"TUCUME",d:"LAMBAYEQUE",p:"LAMBAYEQUE",t:"TUCUME",dir:"AV. FEDERICO VILLARREAL N° 982 (CTRA. FERNANDO BELAUNDE TE",ref:"A MEDIA CDRA. DEL CEMENTERIO JARDINES DE LA PAZ",a:1},
  {l:"BARRANCA",d:"LIMA",p:"BARRANCA",t:"BARRANCA",dir:"JR. ANDRES REYES BUITRON 416. BARRANCA - BARRANCA – LIMA",ref:"A 2 CDRS. DEL PARQUE EL OLVIVAR / A MTRS. DE LA CASA DEL MAESTRO",a:1},
  {l:"PARAMONGA",d:"LIMA",p:"BARRANCA",t:"PARAMONGA",dir:"AV. CENTRAL N° 305 MZ. N1 LT. 17",ref:"URB. MIGUEL GRAU",a:1},
  {l:"SUPE",d:"LIMA",p:"BARRANCA",t:"SUPE",dir:"AV. FRANCISCO VIDAL 1120",ref:"AL COSTADO DE LUBRICENTRO CIRIACO Y MEDIA CDRA. DE LA CRUZ MISIONERA",a:1},
  {l:"ANT PANAM SUR CDRA 11",d:"LIMA",p:"CAÑETE",t:"CHILCA",dir:"ANTIGUA PANAMERICANA SUR CDRA. 11 MZ. 46",ref:"A MEDIA CDRA. DEL HOTEL EL PACÍFICO",a:1},
  {l:"CAÑETE IMPERIAL",d:"LIMA",p:"CAÑETE",t:"IMPERIAL",dir:"JR. AUGUSTO B. LEGUÍA N.º 457",ref:"CEVICHERÍA BRISAS DEL MAR",a:1},
  {l:"CAÑETE SAN VICENTE",d:"LIMA",p:"CAÑETE",t:"SAN VICENTE DE CANET",dir:"AA.HH. VÍCTOR ANDRÉS BELAUNDE MZ. B LT. 12",a:1},
  {l:"JR. SANTA RITA - CAÑETE (POR DEFINIR)",d:"LIMA",p:"CAÑETE",t:"SAN VICENTE DE CANET",dir:"JR. SANTA RITA 399",ref:"CRUCE CON AV. LIBERTADORES"},
  {l:"MALA",d:"LIMA",p:"CAÑETE",t:"MALA",dir:"Av. Marchand # 250",ref:"a unas casas frente a la distribuidora primax gas",a:1},
  {l:"NUEVO IMPERIAL CO",d:"LIMA",p:"CAÑETE",t:"NUEVO IMPERIAL",dir:"FUNDO SANTA ADELA",ref:"AL COSTADO DEL RESTAURANT LA RUTA BRAVA",a:1},
  {l:"CHANCAY",d:"LIMA",p:"HUARAL",t:"CHANCAY",dir:"PROLONGACIÓN SAN MARTÍN N°403 CHANCAY - REFERENCIA: A UNA",ref:"A UNA CDRA. DE LA AV. PANAMERICANA NORTE",a:1},
  {l:"HUARAL",d:"LIMA",p:"HUARAL",t:"HUARAL",dir:"AV. JORGE CHAVEZ 647",ref:"ENTRE LA AV. GRAU Y BOLOGNESI (CERCA AL PARADERO MOTO NATURALES)",a:1},
  {l:"JICAMARCA",d:"LIMA",p:"HUAROCHIRI",t:"SAN ANTONIO",dir:"AV. SINCHI ROCA MZ. P LT. 16A P lote 16A",ref:"CERCA AL ARCO PORTON DE JICAMARCA",a:1},
  {l:"HUACHO AV  INDACOCHEA",d:"LIMA",p:"HUAURA",t:"HUACHO",dir:"AV. MERCEDES INDACOCHEA 1276 HUACHO - HUAURA - LIMA",ref:"INTERSECCIÓN CON PEDRO RUIZ GALLO, A 2 CDRAS. DE LA UNIVERSIDAD NACIONAL JOSÉ FAUSTINO",a:1},
  {l:"HUAURA",d:"LIMA",p:"HUAURA",t:"HUAURA",dir:"AV. LAS MALVINAS MZ. C LOTE 16 URB. EL ROSARIO SUR HUAURA",ref:"A ESPALDAS DE LA PLAZA DE ARMAS, A 1 CDRA. DE LA CALLE LOS ALAMOS",a:1},
  {l:"SALAVERRY HUACHO CO",d:"LIMA",p:"HUAURA",t:"HUACHO",dir:"PROLONGACIÓN salaverry n° 764 huacho - referencia : cruce",ref:"cruce con la av la paz",a:1},
  {l:"SAYAN",d:"LIMA",p:"HUAURA",t:"SAYAN",dir:"CALLE NARANJO N° 211.SAYAN - HUAURA - LIMA",ref:"A MEDIA CDRA. DE LA PLAZA DE ARMAS Y DE LA MUNICIPALIDAD",a:1},
  {l:"01 DE MAYO",d:"LIMA",p:"LIMA",t:"VILLA EL SALVADOR",dir:"AV. 01DE MAYO 1 SECT GP 23 - A MZ N LOTE 13 - V.E.S.",ref:"AV. PASTOR SEVILLA CON AV. 1 DE MAYO A 2 CUADRAS DEL HOSPITAL DE LA SOLIDARIDAD POR LA",a:1},
  {l:"ALMACENES BSF",d:"LIMA",p:"LIMA",t:"PUNTA HERMOSA",dir:"CAR. AUTOPISTA PANAMERICANA SUR N° 2001 (KM. 38) INTERIOR"},
  {l:"ANCON",d:"LIMA",p:"LIMA",t:"ANCON",dir:"CARRETERA SERPENTÍN DE PASAMAYO MZ. G LT. 3 SUBLT. B - ASO",ref:"A 1 CDRA. DEL OVALO DE ANCÓN",a:1},
  {l:"AREA SHALOM EMPRESAS",d:"LIMA",p:"LIMA",t:"LA VICTORIA",dir:"direccion"},
  {l:"ATOCONGO",d:"LIMA",p:"LIMA",t:"SAN JUAN DE MIRAFLORES",dir:"AV. DE LOS HÉROES N° 228 - SAN JUAN DE MIRAFLORES - (ESTAC",a:1},
  {l:"AV  BOLIVAR",d:"LIMA",p:"LIMA",t:"PUEBLO LIBRE",dir:"AV. BOLIVAR 1097",ref:"A MEDIA CDRA. DEL CRUCE AV. GRAL. JOSÉ MARÍA EGUSQUIZA",a:1},
  {l:"AV  CENTRAL  SMP",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. CENTRAL MZ. A LT. 07",ref:"A 5 CDRAS. DEL CRUCE CON AV. TANTAMAYO",a:1},
  {l:"AV  ESPERANZA",d:"LIMA",p:"LIMA",t:"ATE-VITARTE",dir:"AV. ESPERANZA MZ. K LT. 06 LAS AMERICAS - ATE VITARTE - LI",ref:"PASANDO MERCADO RAUCANA",a:1},
  {l:"AV  FLORA TRISTAN",d:"LIMA",p:"LIMA",t:"LA MOLINA",dir:"AV. FLORA TRISTÁN N° 885",ref:"A MEDIA CDRA. DE MOLISALUD",a:1},
  {l:"AV  LA FONTANA",d:"LIMA",p:"LIMA",t:"LA MOLINA",dir:"Av la fontana 440 - La Molina (CC La Rotonda II local 1018",a:1},
  {l:"AV  MARCO PUENTE",d:"LIMA",p:"LIMA",t:"ATE-VITARTE",dir:"AV. MARCO PUENTE LLANOS 309",a:1},
  {l:"AV  NICOLAS DUEÑAS CDRA. 5",d:"LIMA",p:"LIMA",t:"CERCADO LIMA",dir:"AV. NICOLAS DUEÑAS 584 MZ. C LT. 4 – AAHH PRIMERO DE SETIE",ref:"A MEDIA CDRA. DEL CRUCE CON JR. PEDRO GAREZON"},
  {l:"AV  SAN JUAN PAMPLONA ALTA",d:"LIMA",p:"LIMA",t:"SAN JUAN DE MIRAFLORES",dir:"AV. SAN JUAN MZ. 24 LT. 1",ref:"A 3 CDRAS. DEL CRUCE CON AV. SALVADOR ALLENDE",a:1},
  {l:"AV  SANTA ROSA - STA ANITA",d:"LIMA",p:"LIMA",t:"SANTA ANITA",dir:"AV. SANTA ROSA #147 – URB. SANTA ANITA MZ. B1 LT. 08 UNIDA",ref:"A UNA CDRA. DE LA CARRETERA CENTRAL",a:1},
  {l:"AV  TUPAC AMARU KM. 19",d:"LIMA",p:"LIMA",t:"CARABAYLLO",dir:"MZ. 1A - LT. 8 AV. TUPAC AMARU N° 10472",ref:"AL COSTADO DEL COLEGIO CIRO ALEGRÍA",a:1},
  {l:"AV ALAMEDA DEL CORREGIDOR",d:"LIMA",p:"LIMA",t:"LA MOLINA",dir:"AV. ALAMEDA DEL CORREGIDOR MZ. U LT. 19 UI 1 - URB LA CAPI",ref:"A 2 CDRAS. DEL CRUCE CON ALAMEDA DE LOS CÓNDORES",a:1},
  {l:"AV BUENOS AIRES",d:"LIMA",p:"LIMA",t:"PUENTE PIEDRA",dir:"AV. BUENOS AIRES MZ. D",ref:"A 2 CDRAS. DE LA DEMUNA DE PUENTE PIEDRA",a:1},
  {l:"AV CENTRAL SJL",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"AV. CENTRAL MZ R9 LOTE 3 PROGRAMA CIUDAD MRCAL. CACERES",ref:"EN MEDIO DEL CRUCE CON LAS AV. EL MURO Y AMPLIACION ESTE",a:1},
  {l:"AV CIRCUNVALACION SJL",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"AV. CIRCUNVALACIÓN MZ. B-5 LT. 20 AA. HH. SARGENTO FERNAND",ref:"A DOS CDRAS. DEL COLEGIO RAMIRO PRIALE",a:1},
  {l:"AV EL SOL",d:"LIMA",p:"LIMA",t:"ATE-VITARTE",dir:"AV. EL SOL MZ. S LT. 2 ZONA 03 - ASOC. PARQUE INDUSTRIAL E",ref:"A UNA CUADRA Y MEDIA DE LA CARRETERA CENTRAL",a:1},
  {l:"AV HUANDOY CON AV CENTRAL",d:"LIMA",p:"LIMA",t:"LOS OLIVOS",dir:"AV. HUANDOY MZA. 72 LTE. 54 P.J. P.M.V. “CONFRATERNIDAD” -",ref:"A UNA CDRA. DEL CRUCE CON AV. CENTRAL",a:1},
  {l:"AV HUANDOY CON MARAÑON",d:"LIMA",p:"LIMA",t:"LOS OLIVOS",dir:"AV. PRÓCERES",ref:"CRUCE ENTRE AV. HUANDOY Y MARAÑÓN",a:1},
  {l:"AV HUAROCHIRI ENVIOS",d:"LIMA",p:"LIMA",t:"SANTA ANITA",dir:"AV. HUAROCHIRI MZ. D8 LT. 13",ref:"A MEDIA CDRA. DEL CRUCE CON AV. SANTA ROSA"},
  {l:"AV JOSE GRANDA CDRA 38",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. JOSÉ GRANDA 3826 DE LA URB. CONDEVILLA SEÑOR Y VALDIVI",ref:"ENTRE AV. CONDEVILLA Y AV. LOS PRÓCERES",a:1},
  {l:"AV JOSE GRANDA CDRA. 25",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. JOSE GRANDA 2546 - SAN MARTIN DE PORRES -LIMA - LIMA",ref:"A UNA CDRA. DEL ÓVALO JOSE GRANDA Y AV. UNIVERSITARIA",a:1},
  {l:"AV JOSE LEAL CDRA 6",d:"LIMA",p:"LIMA",t:"LINCE",dir:"AV. CORONEL JOSÉ LEAL 648",ref:"PARALELA A LA CDRA. 6 DE LA AV. CANEVARO",a:1},
  {l:"AV JOSE SACO ROJAS",d:"LIMA",p:"LIMA",t:"CARABAYLLO",dir:"AV. JOSÉ SACO ROJAS MZ. A LT. 15 PROGRAMA DE VIVIENDA EL P",ref:"FRENTE AL CHIFA HONG FU Y A 3 CUADRAS DEL GRAN MERCADO EL PINO",a:1},
  {l:"AV LOS PRECURSORES / LAS AMERICAS",d:"LIMA",p:"LIMA",t:"SAN JUAN DE MIRAFLORES",dir:"AV. LOS PRECURSORES MZ. B LT. 17 AA.HH EL INTI",ref:"A 1 CDRA. DEL CRUCE CON AV. LOS PRÓCERES",a:1},
  {l:"AV MALECON  CHECA CDRA. 1",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"AV. MALECÓN MIGUEL CHECA EGUIGUREN N° 167 Y 169 DE LA URB.",ref:"ESQUINA CON AV. GRAN CHIMÚ",a:1},
  {l:"AV MANUEL VALLE",d:"LIMA",p:"LIMA",t:"PACHACAMAC",dir:"AV. MANUEL VALLE SUB - LOTE 2 - 1",ref:"FRENTE AL ESTUDIO DE CANAL 4 (AMERICA TELEVISIÓN)",a:1},
  {l:"AV MEXICO CO",d:"LIMA",p:"LIMA",t:"LA VICTORIA",dir:"AV. MEXICO 1125",a:1},
  {l:"AV MIGUEL GRAU  PAMPLONA ALTA",d:"LIMA",p:"LIMA",t:"SAN JUAN DE MIRAFLORES",dir:"AV. ALMIRANTE MIGUEL GRAU MZ. Y3 LT. 29",ref:"A MEDIA CDRA. DEL MERCADO OLLANTAY PAMPLONAALTA",a:1},
  {l:"AV SANTA ROSA URB LOS ALAMOS",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"Av. Santa Rosa MZ. D1 lote 1 Urb. Los Alamos 2da Etapa - r",ref:"altura de la cuadra 13 del paradero canto grande",a:1},
  {l:"AV TOMAS MARSANO - LA BOLICHERA",d:"LIMA",p:"LIMA",t:"SANTIAGO DE SURCO",dir:"AV. SANTIAGO DE SURCO Nº 4348",ref:"AL LADO DE INTECI SEDE SURCO",a:1},
  {l:"AV TUPAC AMARU CDRA. 57",d:"LIMA",p:"LIMA",t:"COMAS",dir:"AV. TUPAC AMARU 5725-5727 - URB. HUAQUILLAY I ETAPA",ref:"A MEDIA CDRA. DEL BANCO DE LA NACIÓN",a:1},
  {l:"AV UNIV.  RETABLO",d:"LIMA",p:"LIMA",t:"COMAS",dir:"AV. UNIVERSITARIA N° 7241",ref:"EX BOULEVARD DE RETABLO / A 2 CDRAS DEL METRO DE BELAUNDE",a:1},
  {l:"AV UNIVERSITARIA CON IZAGUIRRE",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. UNIVERSITARIA MZ. D LT. 01 ASOCIACIÓN DE VIVIENDA SAN",ref:"A 1 CDRA. DEL CRUCE CON AV. CARLOS IZAGUIRRE"},
  {l:"AV VENEZUELA",d:"LIMA",p:"LIMA",t:"BRENA",dir:"AV. VENEZUELA 1670 - BREÑA",ref:"AL COSTADO DEL POLICLÍNICO DE BREÑA",a:1},
  {l:"AV. 13 DE ENERO",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"AV. 13 DE ENERO Nº2057",ref:"CERCA A LA ESTACIÓN LOS POSTES",a:1},
  {l:"AV. ALFREDO BENAVIDES",d:"LIMA",p:"LIMA",t:"MIRAFLORES",dir:"AV. ALFREDO BENAVIDES 1851 - MIRAFLORES",ref:"AL COSTADO DEL BEMBOS AURORA BENAVIDES"},
  {l:"AV. ANGAMOS",d:"LIMA",p:"LIMA",t:"SAN BORJA",dir:"AV. ANGAMOS ESTE 2521 (EX AV. PRIMAVERA) - CONJUNTO HABITA",ref:"CERCA AL CRUCE DE AV. ANGAMOS ESTE CON AV. PRINCIPAL",a:1},
  {l:"AV. ANGELICA GAMARRA",d:"LIMA",p:"LIMA",t:"LOS OLIVOS",dir:"AV. ANGELICA GAMARRA DE LEON VALVERDE N° 621 URB EL TREBOL",ref:"A LA ALTURA DEL KFC / CRUCE CON AV. ALFA",a:1},
  {l:"AV. ARAMBURU",d:"LIMA",p:"LIMA",t:"SURQUILLO",dir:"AV. ARAMBURÚ 808",ref:"A 2 CDRAS. DE LA AV. PANAMÁ"},
  {l:"AV. ARENALES",d:"LIMA",p:"LIMA",t:"JESUS MARIA",dir:"AV. ARENALES 391",ref:"A 2 CDRAS. DE AV. 28 DE JULIO A LA ESPALDA DE LA UTP"},
  {l:"AV. CANADA",d:"LIMA",p:"LIMA",t:"LA VICTORIA",dir:"AV. CANADÁ 1603",ref:"ENTRE AV. CANADÁ CON AV. AVIACIÓN",a:1},
  {l:"AV. CANEVARO",d:"LIMA",p:"LIMA",t:"SAN JUAN DE MIRAFLORES",dir:"AV. CANEVARO 336 - A",ref:"A 2 CUADRAS DE LA AV. VARGAS MACHUGA Y A UNA CUADRA DE LA FISCALÍA PROVINCIAL PENAL DE",a:1},
  {l:"AV. CANTA CALLAO  CON ALISOS",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. CANTA CALLAO",a:1},
  {l:"AV. CANTA CALLAO CON IZAGUIRRE",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. CANTA CALLAO MZ. A LT. 3 ASOC. BRISAS SANTA ROSA 1RA E",ref:"A MEDIA CDRA. DEL COLEGIO AMISTAD Y/O A CUATRO CDRAS. DE LA AV. CARLOS IZAGUIRRE",a:1},
  {l:"AV. CARLOS IZAGUIRRE CDRA. 14",d:"LIMA",p:"LIMA",t:"LOS OLIVOS",dir:"CALLE DAVID ALVA MANZANA H LOTE 4 URB. CAJABAMBA LOS OLIVO",ref:"ENTRE LA AV. CARLOS IZAGUIRRE CON LA AV. UNIVERSITARIA (FRENTE AL COLEGIO PAMER)",a:1},
  {l:"AV. CARLOS IZAGUIRRE CUADRA 23",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. CARLOS IZAGUIRRE SUB LT. 8",ref:"ENTRE AV. 12 DE OCTUBRE Y AV. SANTA ROSA",a:1},
  {l:"AV. CESAR VALLEJO",d:"LIMA",p:"LIMA",t:"VILLA EL SALVADOR",dir:"AV. CESAR VALLEJO",ref:"FRENTE A ESSALUD, AL COSTADO DEL MERCADO VILLA SUR",a:1},
  {l:"AV. COMANDANTE ESPINAR",d:"LIMA",p:"LIMA",t:"MIRAFLORES",dir:"AV. COMANDANTE ESPINAR 330-MIRAFLORES",ref:"ENTRE EL CRUCE DE CALLE ENRIQUE PALACIOS Y LA AV. COMANDANTE ESPINAR"},
  {l:"AV. DEL MERCADO",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"PROGRAMA CIUDAD MRCAL. CACERES",ref:"A MEDIA CDRA. DEL CRUCE DE AV. DEL MERCADO CON AV. AMPLIACION OESTE",a:1},
  {l:"AV. DOMINICOS CDRA 14",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. LOS DOMINICOS 1460 - URB. LOS CIPRESES MZ. Z LT. 4 - S",ref:"A UNA CDRA. DEL CRUCE CON AV. SANTA ROSA AL LADO DEL MERCADO LOS CIPRESES",a:1},
  {l:"AV. DOS DE OCTUBRE",d:"LIMA",p:"LIMA",t:"LOS OLIVOS",dir:"AV. 2 DE OCTUBRE MZ. H LT. 2 - LOS OLIVOS - PRO",ref:"AV. 2 DE OCTUBRE CON AV. CANTA CALLAO, AL COSTADO DEL CENTRO DE SAlUD PRO",a:1},
  {l:"AV. GERARDO UNGER CDRA 64",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. GERARDO UNGER 6475",ref:"ESQUINA CON AV. 22 DE AGOSTO, LÍMITE CON COMAS",a:1},
  {l:"AV. HUAROCHIRÍ",d:"LIMA",p:"LIMA",t:"SANTA ANITA",dir:"AV. HUAROCHIRÍ MZ. E1 LT. 03 - URB. LOS CEDROS SANTA ANITA",ref:"CRUCE DE AV. HUAROCHIRÍ CON AV. SANTA ANA",a:1},
  {l:"AV. JAVIER PRADO",d:"LIMA",p:"LIMA",t:"SAN BORJA",dir:"AV. JAVIER PRADO ESTE N? 1810 - EST. 05 MZ. A - 1 LT. 04"},
  {l:"AV. JOSE PARDO",d:"LIMA",p:"LIMA",t:"MIRAFLORES",dir:"AV. JOSE PARDO N?533"},
  {l:"AV. LA MARINA",d:"LIMA",p:"LIMA",t:"PUEBLO LIBRE",dir:"AV. LA MARINA 1640 - REFERENCIA : A UNA CUADRA DEL CENTRO",ref:"A UNA CUADRA DEL CENTRO COMERCIAL PLAZA SAN MIGUEL",a:1},
  {l:"AV. LA MOLINA CDRA. 35",d:"LIMA",p:"LIMA",t:"LA MOLINA",dir:"AV. LA MOLINA (EXAV. LA UNIVERSIDAD) #3551 TDA -7 MZ. H SU",ref:"A MEDIA CDRA. DEL CRUCE CON AV. EL SOL",a:1},
  {l:"AV. LAS PALMERAS",d:"LIMA",p:"LIMA",t:"LOS OLIVOS",dir:"AV. LAS PALMERAS N° 5236 URB. VILLA NORTE - LOS OLIVOS",a:1},
  {l:"AV. LAS TORRES - LURIGANCHO CHOSICA (POR DEFINIR)",d:"LIMA",p:"LIMA",t:"LURIGANCHO",dir:"AV. LAS TORRES SUB. LT. 18A - 1D",ref:"AL FRENTE DEL CRUCE CON AV. MEDIA LUNA"},
  {l:"AV. LIMA - VMT",d:"LIMA",p:"LIMA",t:"VILLA MARIA DEL TRIUNFO",dir:"AV. LIMA 2208 JOSÉ GÁLVEZ- VILLA MARÍA DEL TRIUNFO",ref:"A DOS CDRAS. DE LA CURVA JOSÉ GÁLVEZ",a:1},
  {l:"AV. LIMA CDRA 38",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. LIMA 3899 - SMP",ref:"A 3 CDRAS. DEL TOTTUS DE QUILCA CON AV. LIMA",a:1},
  {l:"AV. LOS PLATINOS",d:"LIMA",p:"LIMA",t:"LOS OLIVOS",dir:"AV. LOS PLATINOS N°. 259",ref:"A DOS CDRAS. Y MEDIA DE LA AV. ALFREDO MENDIOLA Y",a:1},
  {l:"AV. PACHACUTEC - VMT (POR DEFINIR)",d:"LIMA",p:"LIMA",t:"VILLA MARIA DEL TRIUNFO",dir:"AV. PACHACÚTEC N° 4465",ref:"AL FRENTE DEL CRUCE CON AV. 01 DE MAYO"},
  {l:"AV. PASTOR SEVILLA",d:"LIMA",p:"LIMA",t:"VILLA EL SALVADOR",dir:"MZ. B LT. 3 BARRIO 3 SECTOR 2 - 4TA ETAPA - VES",ref:"POR EL ÓVALO CERRO LOMAS, FRENTE AL COLEGIO VIRGEN DEL ROSARIO",a:1},
  {l:"AV. PERU 15",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"Av. Perú 1589",ref:"a dos cuadras del CruCe con la Av. Canadá",a:1},
  {l:"AV. PRIMAVERA 120",d:"LIMA",p:"LIMA",t:"SANTIAGO DE SURCO",dir:"Av. Primavera Nº 120 Tda. A-21 – Urb. Tambo de Monterrico"},
  {l:"AV. PRIMAVERA 1314",d:"LIMA",p:"LIMA",t:"SANTIAGO DE SURCO",dir:"AV. PRIMAVERA N° 1314",ref:"CRUCE JR. EL POLO"},
  {l:"AV. PRIMAVERA 264",d:"LIMA",p:"LIMA",t:"SANTIAGO DE SURCO",dir:"AV. PRIMAVERA 264 TDA 187 C.C. CHACARILLA – SANTIAGO DE SU",ref:"C.C. CHACARILLA PRIMER PISO (PUERTA PRINCIPAL DEL CENTRO COMERCIAL)"},
  {l:"AV. PRINCIPAL",d:"LIMA",p:"LIMA",t:"SURQUILLO",dir:"LT. 12 MZ. G",ref:"CRUCE CON A. MANUEL VILLARÁN",a:1},
  {l:"AV. REVOLUCIÓN VES (POR DEFINIR)",d:"LIMA",p:"LIMA",t:"VILLA EL SALVADOR",dir:"AV. REVOLUCIÓN MZ. J LT. 19",ref:"CERCA AL CRUCE CON AV. JOSE CARLOS MARIATEGUI"},
  {l:"AV. ROOSEVELT",d:"LIMA",p:"LIMA",t:"MIRAFLORES",dir:"AV. ROOSEVELT 6297 (ANTES REP. PANAMÁ) - MIRAFLORES"},
  {l:"AV. SAN FELIPE",d:"LIMA",p:"LIMA",t:"JESUS MARIA",dir:"AV. SAN FELIPE 1195 - JESÚS MARÍA"},
  {l:"AV. SAN LORENZO",d:"LIMA",p:"LIMA",t:"PUENTE PIEDRA",dir:"AV. SAN LORENZO MZ C LT 20 - ADP VIRGEN DE COPACABANA",a:1},
  {l:"AV. SANTA ROSA CRUCE AV. EL SOL",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"AV. SANTA ROSA DE LIMA MZ. D LT. 4 - AAHH 2 DE SETIEMBRE -",ref:"A TRES CDRAS. DEL CRUCE CON AV. EL SOL",a:1},
  {l:"AV. TOMÁS MARSANO",d:"LIMA",p:"LIMA",t:"SANTIAGO DE SURCO",dir:"AV. TOMÁS MARSANO 3767 - SANTIAGO DE SURCO",ref:"A MEDIA CUADRA DE LA ESTACIÓN DE TREN AYACUCHO"},
  {l:"AV. TRAPICHE",d:"LIMA",p:"LIMA",t:"COMAS",dir:"AV. TRAPICHE 886 A 16 2P 2 - URB. PINAR",ref:"FRENTE AL COMPLEJO DEPORTIVO WALON",a:1},
  {l:"AV. TUPAC AMARU KM. 23.5",d:"LIMA",p:"LIMA",t:"CARABAYLLO",dir:"AV. TÚPAC AMARU KM. 23.5 - CARABAYLLO",ref:"FRENTE A LA IGLESIA DE MORMONES - A UNA CDRA. DEL ÚLTIMO PARADERO DEL RÁPIDO",a:1},
  {l:"AV. UNIV. PARQUE SINCHI ROCA",d:"LIMA",p:"LIMA",t:"COMAS",dir:"AV. UNIVERSITARIA NORTE MZN. Q1 LTE. 030 URB. PRIMAVERA",ref:"A MEDIA CDRA. DEL INGRESO AL PARQUE ZONA SINCHI ROCA",a:1},
  {l:"AV. UNIVERSITARIA CDRA. 16",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. UNIVERSITARIA 1619 - URB. MARIA GRACIA DE ANTARES MZ.",ref:"FRENTE AL PLAZA VEA DE UNIVERSITARIA CON TOMAS VALLE",a:1},
  {l:"AV. VICTOR MALASQUEZ - PACHACAMAC (POR DEFINIR)",d:"LIMA",p:"LIMA",t:"PACHACAMAC",dir:"AV. VICTOR MALASQUEZ MZ. B LT. 16 – ASOCIACIÓN DE VIVIENDA",ref:"A 2 CDRAS. DEL CRUCE CON AV. UNIÓN"},
  {l:"AV. VILLA MARIA",d:"LIMA",p:"LIMA",t:"VILLA MARIA DEL TRIUNFO",dir:"AV VILLA MARIA MZ. G12 LT. 9 - B PS 1 SECT. VILLA MARIA DE",ref:"AV. VILLA MARIA A 2 CUADRAS DE LA MUNICIPALIDAD DE VMT Y AL COSTADO DE ESSALUD",a:1},
  {l:"AVIACION 2819",d:"LIMA",p:"LIMA",t:"SAN BORJA",dir:"AV. AVIACIÓN 2819",ref:"AL FRENTE DE BEMBOS",a:1},
  {l:"AVIACION 2999",d:"LIMA",p:"LIMA",t:"SAN BORJA",dir:"AV. AVIACIÓN 2999",ref:"A 1 CDRA. DE LA ESTACIÓN DEL TREN SAN BORJA SUR"},
  {l:"AÑO NUEVO",d:"LIMA",p:"LIMA",t:"COMAS",dir:"AV. TUPAC AMARU N° 7837- 7839 MZ. C LT. 010 URB. POPULAR S",ref:"A UNA CDRA. DE LA ENTRADA DE COLLIQUE",a:1},
  {l:"BAYOVAR",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"AV. FERNANDO WIESSE MZ. E8. LOTE 38B",ref:"AUXILIAR PRÓCERES DE LA INDEPENDENCIA, AL FRENTE DE LA UNIVERSIDAD SAN MARCOS –",a:1},
  {l:"CAJA DISTRIBUCION LIMA",d:"LIMA",p:"LIMA",t:"CERCADO LIMA"},
  {l:"CAJA TRANSPORTE MEXICO",d:"LIMA",p:"LIMA",t:"LA VICTORIA",dir:"cargando"},
  {l:"CALLE A  CON AV INDUSTRIAL",d:"LIMA",p:"LIMA",t:"INDEPENDENCIA",dir:"CALLE A",ref:"A 1 CDRA. DEL CRUCE CON AV. INDUSTRIAL (LATERAL DE MEGAPLAZA)",a:1},
  {l:"CALLE BERLIN",d:"LIMA",p:"LIMA",t:"MIRAFLORES",dir:"Calle Berlín 219 - Miraflores"},
  {l:"CALLE LAS BEGONIAS",d:"LIMA",p:"LIMA",t:"SAN ISIDRO",dir:"CALLE LAS BEGONIAS 774 - SAN ISIDRO"},
  {l:"CALLE MIGUEL DASSO",d:"LIMA",p:"LIMA",t:"SAN ISIDRO",dir:"CALLE MIGUEL DASSO 126 - SAN ISIDRO",ref:"EN EL CRUCE DE CALLE LEONIDAS YEROVI Y CALLE MIGUEL DASSO"},
  {l:"CAMPOY",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"AV. MALECÓN CHECA MZ. B LT. 7",ref:"A 1 CDRA. DEL CRUCE DE AV. MALECÓN CHECA CON AV. SAN MARTÍN",a:1},
  {l:"CANTO GRANDE",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"CALLE SAN MARTIN CON AV. COMERCIAL NORTE 189 - SAN JUAN DE",ref:"A 1/2 CUADRA DE LA AV 6 DE CANTO GRANDE - AL COSTADO DEL PLAY PARK (PARQUE BOLOGNESI)",a:1},
  {l:"CARABAYLLO ESTABLO",d:"LIMA",p:"LIMA",t:"CARABAYLLO",dir:"AV. TUPAC AMARU N? 441 - 443",ref:"PARADERO ESTABLO, A UNA CUADRA DE LA URB. SANTA ISABEL",a:1},
  {l:"CD. TALLERES-HUACHIPA",d:"LIMA",p:"LIMA",t:"LURIGANCHO",dir:"v"},
  {l:"CHORRILLOS CO",d:"LIMA",p:"LIMA",t:"CHORRILLOS",dir:"AV. SANTA ANITA N.° 580",ref:"AL COSTADO DEL MERCADO SANTA ANITA, CRUCE CON SAN GENARO",a:1},
  {l:"CHORRILLOS LOS FAISANES",d:"LIMA",p:"LIMA",t:"CHORRILLOS",dir:"AV. LOS FAISANES 420",ref:"AL COSTADO DE LA TIENDA JOHN HOLDEN",a:1},
  {l:"CHOSICA",d:"LIMA",p:"LIMA",t:"LURIGANCHO",dir:"EL SOL 124 (PARQUE ECHENIQUE) LURIGANCHO - CHOSICA",a:1},
  {l:"CIENEGUILLA KM. 14.5",d:"LIMA",p:"LIMA",t:"CIENEGUILLA",dir:"AV. ARTERIAL HUAROCHIRI D MZ. B LT. 19",ref:"AL COSTADO DE LA TIENDA MASS",a:1},
  {l:"CORPAC",d:"LIMA",p:"LIMA",t:"SAN ISIDRO",dir:"CALLE 21 785",ref:"AL COSTADO DEL MINISTERIO DEL INTERIOR"},
  {l:"CRUZ DE MOTUPE",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"AV. FERNANDO WIESSE MZ. Q LOTE 1 AA.HH. CRUZ DE MOTUPE",a:1},
  {l:"EL PROGRESO KM 22",d:"LIMA",p:"LIMA",t:"CARABAYLLO",dir:"AV. TUPAC AMARU 3493 – P.J. EL PROGRESO (PARTE BAJA) MZ. K",ref:"A UNA CDRA. DEL CRUCE CON LA AV. MANUEL PRADO",a:1},
  {l:"FIORI",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. MIGUEL ANGEL N° 235 - URB. FIORI 4TA ETAPA MZ. N-1 LT.",ref:"A 1 CDRA. DEL CRUCE CON AV. MARCO POLO",a:1},
  {l:"GERMÁN AGUIRRE",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. GERMAN AGUIRRE UGARTE 649 URB. SAN GERMAN - SAN MARTIN",ref:"A LA ALTURA DE LA CUADRA 6 DE LA AV. GERMAN AGUIRRE Y A 3 CUADRAS DE AV. TOMAS VALLE",a:1},
  {l:"HIGUERETA",d:"LIMA",p:"LIMA",t:"SANTIAGO DE SURCO",dir:"Calle Barlovento N° 134 REFERENCIA: A 3 CDRAS DE POLVOS RO",ref:"A 3 CDRAS DE POLVOS ROSADOS, CERCA AL ÓVALO HIGUERETA, surco",a:1},
  {l:"HUACHIPA CO",d:"LIMA",p:"LIMA",t:"LURIGANCHO",dir:"HUACHIPA ESTE - MANZANA A18 LOTE 1",ref:"AL COSTADO DE INDUSTRIAS ELÉCTRICAS KBA",a:1},
  {l:"HUACHIPA CO 2",d:"LIMA",p:"LIMA",t:"LURIGANCHO",dir:"HUACHIPA ESTE - MANZANA A18 LOTE 1",ref:"AL COSTADO DE INDUSTRIAS ELÉCTRICAS KBA"},
  {l:"HUAYCAN  EL DESCANSO",d:"LIMA",p:"LIMA",t:"ATE-VITARTE",dir:"AV. JOSE CARLOS MARIATEGUI MZA. B LTE 06",ref:"CRUCE CON LA AV. LOS INCAS",a:1},
  {l:"HUAYCAN AV HORACIO ZEVALLOS",d:"LIMA",p:"LIMA",t:"ATE-VITARTE",dir:"AV. HORACIO ZEBALLOS MZ. V LT. 12 PROG. VIV. RESIDENCIAL P",ref:"FRENTE AL CIRCUITO DE MANEJO GARCILASO DE LA VEGA",a:1},
  {l:"HUAYCAN AV JOSE C MARIATEGUI",d:"LIMA",p:"LIMA",t:"ATE-VITARTE",dir:"AV. JOSÉ CARLOS MARIÁTEGUI Z. E LT. 23 UCV 5 (ZONA COMERCI",ref:"A DOS CDRAS. DEL CRUCE CON AV. 15 DE JULIO",a:1},
  {l:"HUAYCAN ENTRADA",d:"LIMA",p:"LIMA",t:"ATE-VITARTE",dir:"AV. ANDRÉS AVELINO CÁCERES MZ G LT. 14",ref:"A UNA CDRA. DE LA CTRA. CENTRAL, PARADERO EL LAVADERO",a:1},
  {l:"JESUS MARIA",d:"LIMA",p:"LIMA",t:"JESUS MARIA",dir:"AV. MARISCAL LUZURIAGA 584-586 JESÚS MARÍA - LIMA",ref:"A CUADRA Y MEDIA DEL PARQUE SAN JOSÉ, PARALELO A LA AV. MELLO FRANCO",a:1},
  {l:"JIRON ANCASH",d:"LIMA",p:"LIMA",t:"EL AGUSTINO",dir:"JR. ANCASH MZ. B LT. 11 AAHH ANCIETA ALTA",ref:"FRENTE AL INGRESO DE AGUSTINO PLAZA",a:1},
  {l:"JR CASANOVA CON PETIT THOUARS",d:"LIMA",p:"LIMA",t:"LINCE",dir:"JR. DOMINGO CASANOVA N°318 LINCE - LIMA",ref:"CRUCE CON PETIT THOUARS",a:1},
  {l:"JR CHINCHAYSUYO CDRA 4",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"JR. CHINCHAYSUYO 468 ZARATE",ref:"A 1 CDRA. DE TIENDAS 3 A",a:1},
  {l:"JR. HUARAZ -  BREÑA",d:"LIMA",p:"LIMA",t:"BRENA",dir:"JR. HUARAZ 1633",ref:"EN MEDIO DEL CRUCE DE JR. GRAL ORBEGOSO Y JR. CENTENARIO CON JR. HUARAZ",a:1},
  {l:"JR. LUNA PIZARRO",d:"LIMA",p:"LIMA",t:"LA VICTORIA",dir:"JR. LUNA PIZARRO N° 701 - LA VICTORIA",ref:"ESQUINA HIPÓLITO UNANUE"},
  {l:"JR. RAYMONDI",d:"LIMA",p:"LIMA",t:"LA VICTORIA",dir:"JR. ANTONIO RAYMONDI NRO. 113",a:1},
  {l:"LA CINCUENTA",d:"LIMA",p:"LIMA",t:"INDEPENDENCIA",dir:"AV. TUPAC AMARU N° 4708 - 4710",ref:"A UNA CDRA. DEL PARADERO ESTACIÓN NARANJAL",a:1},
  {l:"LA CURVA DE MANCHAY",d:"LIMA",p:"LIMA",t:"PACHACAMAC",dir:"AV. PROLONGACIÓN DE LA AV. LA MOLINA MZ. E LOTE 21. AH PAU",ref:"A MEDIA CDRA. DE MI BANCO",a:1},
  {l:"LARCOMAR",d:"LIMA",p:"LIMA",t:"MIRAFLORES",dir:"MALECÓN DE LA RESERVA 610",ref:"SÓTANO NIVEL A",a:1},
  {l:"LAS CONCHITAS",d:"LIMA",p:"LIMA",t:"VILLA MARIA DEL TRIUNFO",dir:"AV. PACHACUTEC 6779",ref:"A UNA CDRA. DEL GRIFO REPSOL LAS CONCHITAS",a:1},
  {l:"LAS DELICIAS DE VILLA",d:"LIMA",p:"LIMA",t:"CHORRILLOS",dir:"AV. 12 DE OCTUBRE MZ. A - 03",ref:"A DOS CUADRAS DE LA AV. DEFENSORES DEL MORRO (EX AV. HUAYLAS)",a:1},
  {l:"LIMA AV TINGO MARÍA",d:"LIMA",p:"LIMA",t:"CERCADO LIMA",dir:"AV. TINGO MARÍA N°1252-A - CERCADO DE LIMA - LIMA",ref:"A MEDIA CDRA. DEL CRUCE CON JR. GRAL. ORBEGOSO",a:1},
  {l:"LOS FRESNOS",d:"LIMA",p:"LIMA",t:"LA MOLINA",dir:"AV. LOS FRESNOS 1305 TIENDA 2 - URB. PORTADA DEL SOL I ETA",ref:"A 3 CDRAS. DEL ÓVALO DE LOS CÓNDORES",a:1},
  {l:"LOS PINOS",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"MZ. B1 LT. 25 URBANIZACIÓN LOS PINOS SAN JUAN DE LURIGANCH",ref:"AV. FERNANDO WIESSE - CERCA A LA ESTACIÓN SAN MARTÍN",a:1},
  {l:"LOS SAUCES",d:"LIMA",p:"LIMA",t:"ATE-VITARTE",dir:"AV. SANTA ROSA N°773 MANZANA “A” LOTE 6 URB LOS SAUCES - A",ref:"CRUCE CON LA AV SEPARADORA INDUSTRIAL",a:1},
  {l:"MAGDALENA DEL MAR",d:"LIMA",p:"LIMA",t:"MAGDALENA DEL MAR",dir:"JR. AYACUCHO N° 756",ref:"A UNA CDRA. DEL MERCADO MODELO DE MAGDALESY A 3 CDRAS. DE LA IGLESIA CÚPULA DE SUCRE",a:1},
  {l:"MALVINAS - JR. GARCIA VILLóN",d:"LIMA",p:"LIMA",t:"CERCADO LIMA",dir:"JR. PRESBÍTERO GARCÍA VILLON NRO. 560 CERCADO LIMA - LIMA",ref:"A LA ALTURA DE LA CDRA. 5 DE AV. OSCAR R. BENAVIDES (EX AV. COLONIAL), EN MEDIO DE LAS",a:1},
  {l:"MALVINAS - JR. RICARDO TRENEMAN",d:"LIMA",p:"LIMA",t:"CERCADO LIMA",dir:"JR. RICARDO TRENEMAN N° 920",ref:"DENTRO DEL LOCAL FARENET"},
  {l:"MANCHAY TRES MARIAS",d:"LIMA",p:"LIMA",t:"PACHACAMAC",dir:"AV. VICTOR MALASQUEZ MZ. B11 SUB-LOTE 06-A - AAHH CENTRO P",ref:"A MEDIA CDRA. DEL PARADERO",a:1},
  {l:"MARIA AUXILIADORA",d:"LIMA",p:"LIMA",t:"SAN JUAN DE MIRAFLORES",dir:"AV. LOS HÉROES 1140 - SJM",ref:"UNA CDRA. ANTES DEL HOSPITAL MARÍA AUXILIADORA",a:1},
  {l:"MEGAPLAZA CHORRILLOS",d:"LIMA",p:"LIMA",t:"CHORRILLOS",dir:"AV. ALAMEDA SUR 5",ref:"CRUCE DE AV. ALAMEDA SUR CONAV. ALAMEDA SAN MARCOS",a:1},
  {l:"MEGAPLAZA INDEPENDENCIA",d:"LIMA",p:"LIMA",t:"INDEPENDENCIA",dir:"CENTRO COMERCIAL MEGA PLAZA AV. ALFREDO MENDIOLA 3698 LIMA",ref:"PRIMER PISO DE MEGA PLAZA / AL COSTADO DEL ESTACIONAMIENTO DE BICICLETA",a:1},
  {l:"NUEVA ESPERANZA VMT",d:"LIMA",p:"LIMA",t:"VILLA MARIA DEL TRIUNFO",dir:"AV. 26 DE NOVIEMBRE",ref:"A 3 CDRAS. DEL MERCADO VIRGEN DE LOURDES",a:1},
  {l:"NUEVO LURIN",d:"LIMA",p:"LIMA",t:"LURIN",dir:"AV. ANTIGUA PANAMERICANA SUR KM 37 MZ C LT 17 - FUNDO LAS",ref:"a cuadra y media del mercado virgen de las mercedes",a:1},
  {l:"OVALO PUENTE PIEDRA",d:"LIMA",p:"LIMA",t:"PUENTE PIEDRA",dir:"AV. MIGUEL GRAUÂ MZ. A LT. 07 Y 08 URB. SAN MARTIN DE PORR",ref:"ESPALDAS DE TOTTUS DE PUENTE PIEDRA",a:1},
  {l:"PARQUE LA MOLINA",d:"LIMA",p:"LIMA",t:"LA MOLINA",dir:"AV. LA MOLINA 2448",ref:"ESTACIONAMIENTO NIVEL -3",a:1},
  {l:"PESQUERO",d:"LIMA",p:"LIMA",t:"VILLA MARIA DEL TRIUNFO",dir:"AV. PACHACUTEC N° 3548",ref:"FRENTE A REAL PLAZA, A 1 CDRA. DE MAYORSA",a:1},
  {l:"PLAZA NORTE ENTREGAS",d:"LIMA",p:"LIMA",t:"INDEPENDENCIA",dir:"Av. GERARDO UNGER NRO. 6917 INT. LB 19",a:1},
  {l:"PLAZA NORTE S. EXPRESS",d:"LIMA",p:"LIMA",t:"INDEPENDENCIA",dir:"Av. GERARDO UNGER NRO. 6917 INT. LB 19"},
  {l:"PRO",d:"LIMA",p:"LIMA",t:"LOS OLIVOS",dir:"AV. LOS PRÓCERES MZ. PP2 LT.21",a:1},
  {l:"PUENTE ARICA",d:"LIMA",p:"LIMA",t:"PUENTE PIEDRA",dir:"PANAMERICANA NORTE KM 32.5",a:1},
  {l:"PUENTE LURIN",d:"LIMA",p:"LIMA",t:"LURIN",dir:"ANTIGUA PANAMERICANA SUR",ref:"A CDRA. Y MEDIA DEL CRUCE CON AV. SANTA CRUZ",a:1},
  {l:"PUENTE NUEVO",d:"LIMA",p:"LIMA",t:"EL AGUSTINO",dir:"AV 1° DE MAYO 3071 - URB HUANCAYO referencia : FRENTE AL G",ref:"FRENTE AL GRIFO REPSOL",a:1},
  {l:"PUENTE SANTA ANITA",d:"LIMA",p:"LIMA",t:"ATE-VITARTE",dir:"Av. Nicolás Ayllón N° 3080 - Ate vitarte",a:1},
  {l:"PUNTA HERMOSA",d:"LIMA",p:"LIMA",t:"PUNTA HERMOSA",dir:"AV. GARCIA RADA MZ.B LT.04",ref:"A UNA CDRA. DEL PARADERO PEATONAL DE PUNTA HERMOSA",a:1},
  {l:"REAL PLAZA SALAVERRY",d:"LIMA",p:"LIMA",t:"JESUS MARIA",dir:"CENTRO COMERCIAL REAL PLAZA SALAVERRY",ref:"FRENTE A LA ESCUELA DE POSTGRADO UTP",a:1},
  {l:"REP. DE PANAMA",d:"LIMA",p:"LIMA",t:"SURQUILLO",dir:"AV REPÚBLICA DE PANAMÁ N° 5115",ref:"costado del grifo Repsol",a:1},
  {l:"REPARTO SAN LUIS",d:"LIMA",p:"LIMA",t:"CIENEGUILLA",dir:"SAN LUIS"},
  {l:"RIMAC AV. AMANCAES",d:"LIMA",p:"LIMA",t:"RIMAC",dir:"Av. Amancaes Nro. 644 urb. Ciudad y campo - Rimac",a:1},
  {l:"RIMAC GUARDIA REPUBLICANA CDRA. 9",d:"LIMA",p:"LIMA",t:"RIMAC",dir:"SECCIÓN INMOBILIARIA N°2 – PRIMER PISO LT. 11 DE LA MZ. 2",ref:"A UNA CDRA. DEL CRUCE CON AV. FELIPE ARANCIBIA",a:1},
  {l:"RIV. NAVARRETE",d:"LIMA",p:"LIMA",t:"SAN ISIDRO",dir:"AV. RIVERA NAVARRETE 465",ref:"CRUCE DE JAVIER PRADO CON RIVERA NAVARRETE"},
  {l:"SANTA CLARA",d:"LIMA",p:"LIMA",t:"ATE-VITARTE",dir:"Av. Pedro Ruíz Gallo Mz. H Lt. 3. Asoc. Viv. Villa San Lui",a:1},
  {l:"SANTA MARÍA DE HUACHIPA",d:"LIMA",p:"LIMA",t:"LURIGANCHO",dir:"AV. CIRCUNVALACIÓN MZ. A LT. 1 - D C - P SANTA MARÍA DE HU",ref:"ENTRE LA AV. CIRCUNVALACIÓN Y LA AV. HUACHIPA",a:1},
  {l:"SANTA ROSA",d:"LIMA",p:"LIMA",t:"SANTA ROSA",dir:"MZ. L 23 URB. COOVITIOMAR",ref:"CRUCE DE INGRESO A SANTA ROSA Y/O AL COSTADO DE IMAGEN DE SANTA ROSA",a:1},
  {l:"SANTO DOMINGO",d:"LIMA",p:"LIMA",t:"CARABAYLLO",dir:"AV. A MZ. L2 LT. 20 URB. SANTO DOMINGO – VI ETAPA CARABAYL",ref:"EN EL CRUCE DE LAS AV. CHILLON TRAPICHE Y AV. CAMINO REAL",a:1},
  {l:"SEGUNDA DE PRO",d:"LIMA",p:"LIMA",t:"LOS OLIVOS",dir:"AV. ALFREDO MENDIOLA 8161 URB. PRO",ref:"A UNA CDRA. DEL COLEGIO JOSÉ MARÍA ARGUEDAS"},
  {l:"SJL- LAS FLORES",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"AV. CANTO GRANDE N°. 2570 - URB. GANIMEDES",ref:"A 3 CDRAS. DE PLAZA VEA",a:1},
  {l:"SJL-AV.PROCERES",d:"LIMA",p:"LIMA",t:"SAN JUAN DE LURIGANCHO",dir:"AV. PRÓCERES DE LA INDEPENDENCIA NRO. 1295 - 1299 REFERENC",ref:"AL COSTADO DEL BANCO DE LA NACIÓN DE AV. LOS TUSILAGOS OESTE",a:1},
  {l:"SMP AV BERTELLO",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. ALEJANDRO BERTELLO BOLLATI MZ. H LT. 2-A - ASOC. DE VI",ref:"A MEDIA CDRA. DEL CRUCE CON AV. CANTA CALLAO",a:1},
  {l:"SMP AV PACASMAYO",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. PACASMAYO MZ. A LT. 03 – URB. SANTA FE DE NARANJAL",ref:"A 3 CDRAS. DEL CRUCE CON AV. EL SOL DE NARANJAL"},
  {l:"SMP-AV. PROCERES",d:"LIMA",p:"LIMA",t:"SAN MARTIN DE PORRES",dir:"AV. PRÓCERES N° 588 URB. COVICEM",ref:"A 2 CDRAS. DE TOMÁS VALLE",a:1},
  {l:"SURCO MATEO PUMACAHUA",d:"LIMA",p:"LIMA",t:"SANTIAGO DE SURCO",dir:"AV. SAN JUAN MZ A LOTE 01 MATEO PUMACAHUA - SURCO",ref:"A 2 CUADRAS DE LA AV. TUPAC AMARU ENTRE EL LÍMITE DE CHORRILLOS Y SURCO",a:1},
  {l:"TUNGASUCA",d:"LIMA",p:"LIMA",t:"CARABAYLLO",dir:"AV. TRAPICHE MZ. P LT. 48",ref:"AUX. AV. CHIMPU OCLLO CON AUX. CHILLÓN TRAPICHE, A 1 CUADRA DEL MERCADO QATUNA",a:1},
  {l:"Terminal de prueba sistemas",d:"LIMA",p:"LIMA",t:"VILLA EL SALVADOR",dir:"av prueba."},
  {l:"URB SANTA ELVIRA",d:"LIMA",p:"LIMA",t:"ATE-VITARTE",dir:"AV. FERROCARRIL MZ. C LT. 19 PARCELA 3",ref:"A MEDIA CDRA. DEL CRUCE CON AV. DE LA CULTURA",a:1},
  {l:"URB UNIVERSAL",d:"LIMA",p:"LIMA",t:"SANTA ANITA",dir:"JR. CESAR VALLEJO 302 MZ. B1 LT. 02 URB UNIVERSAL",ref:"A 1 CDRA. DEL CRUCE CON AV. TUPAC AMARU",a:1},
  {l:"URB. REPARTICIÓN",d:"LIMA",p:"LIMA",t:"COMAS",dir:"AV. TUPAC AMARU 3184 URB. REPARTICION",ref:"A MEDIA CDRA. DE AV. VICTOR ANDRES BELAUNDE Y/O FRENTE A DOLLARCITY",a:1},
  {l:"ZAPALLAL",d:"LIMA",p:"LIMA",t:"PUENTE PIEDRA",dir:"AV. ANCÓN 678",ref:"A LA ESPALDA DEL PRECIO UNO DE FUNDICION",a:1},
  {l:"ÓVALO MARIÁTEGUI",d:"LIMA",p:"LIMA",t:"VILLA EL SALVADOR",dir:"AV. PASTOR SEVILLA SECT. 6 - GP 7 - MZ. A - LOTE 05 - V.E.",ref:"A 2 CUADRAS DEL ÓVALO MARIÁTEGUI CON 3 DE OCTUBRE",a:1},
  {l:"CHURÍN",d:"LIMA",p:"OYON",t:"CHURIN",dir:"AV. VÍA DE EVITAMIENTO N° N/S CHURÍN - OYÓN - LIMA",ref:"A MEDIA CDRA. DE LA PLAZA DE ARMAS Y DE LA MUNICIPALIDAD",a:1},
  {l:"PUERTO YURIMAGUAS",d:"LORETO",p:"ALTO AMAZONAS",t:"YURIMAGUAS",dir:"Shalom"},
  {l:"YURIMAGUAS",d:"LORETO",p:"ALTO AMAZONAS",t:"YURIMAGUAS",dir:"CALLE JORGE CHÁVEZ N° 300",ref:"ESQUINA CON PROGRESO, AL COSTADO DE ENAPU",a:1},
  {l:"AEROPUERTO IQUITOS",d:"LORETO",p:"MAYNAS",t:"IQUITOS",dir:"Aeropuerto Coronel Francisco secada Vignetta"},
  {l:"AV JOSE A. QUIÑONES",d:"LORETO",p:"MAYNAS",t:"IQUITOS SAN JUAN BAUTISTA",dir:"AV. JOSÉ ABELARDO QUIÑONES # 2475 SAN JUAN BAUTISTA - MAYN",ref:"FRENTE A LA UNIVERSIDAD CIENTÍFICA DEL PERÚ (UCP)",a:1},
  {l:"AV PARTICIPACION PARCELA",d:"LORETO",p:"MAYNAS",t:"IQUITOS SAN JUAN BAUTISTA",dir:"AV. PARTICIPACIÓN PARCELA 9-A SAN JUAN BAUTISTA - MAYNAS -",ref:"FRENTE AL LAVADERO OSITO Y A MEDIA CDRA. DEL PARQUE 1 DE ENERO",a:1},
  {l:"CTRA IQUITOS NAUTA",d:"LORETO",p:"MAYNAS",t:"IQUITOS SAN JUAN BAUTISTA",dir:"CARRETERA IQUITOS NAUTA",ref:"AL COSTADO DE LA DISTRIBUIDORA AMAZON GAS",a:1},
  {l:"IQUITOS  AV TUPAC AMARU",d:"LORETO",p:"MAYNAS",t:"IQUITOS",dir:"AV. TUPAC AMARU CON - CALLE LOURDES DE LEÓN #479 IQUITOS M",ref:"FRENTE A LA BOTICA THIAGOFAMA",a:1},
  {l:"IQUITOS CO JR. BOLOGNESI",d:"LORETO",p:"MAYNAS",t:"IQUITOS",dir:"JR. FRANCISCO BOLOGNESI #941 CON JR. BERMÚDEZ",ref:"FRENTE A LA UNIVERSIDAD NACIONAL DE LA AMAZONIA PERUANA",a:1},
  {l:"IQUITOS JR PABLO ROSSEL",d:"LORETO",p:"MAYNAS",t:"IQUITOS",dir:"JR PABLO ROSSEL 590 CON NANAY",ref:"FRENTE AL CETPRO AMERICAN COMPUTER",a:1},
  {l:"PUERTO IQUITOS",d:"LORETO",p:"MAYNAS",t:"IQUITOS",dir:"......."},
  {l:"PUNCHANA",d:"LORETO",p:"MAYNAS",t:"PUNCHANA",dir:"CALLE BORJA N°648 PUNCHANA - MAYNAS - LORETO",ref:"AL COSTADO DE LA FARMACIA SAN CARLOS CENTRO MÉDICO",a:1},
  {l:"IBERIA",d:"MADRE DE DIOS",p:"TAHUAMANU",t:"IBERIA",dir:"AV. JORGE CHAVEZ MZ. H1 SUB LOTE 11-B",ref:"A UNA CDRA. DE LA EMPRESA REAL DORADO / A UNA CDRA. Y MEDIA DE LA AV JOSE ALDAMIZ",a:1},
  {l:"AEROPUERTO PUERTO MALDONADO",d:"MADRE DE DIOS",p:"TAMBOPATA",t:"TAMBOPATA",dir:"Aeropuerto Internacional Padre Aldamiz"},
  {l:"AV 15 DE AGOSTO",d:"MADRE DE DIOS",p:"TAMBOPATA",t:"TAMBOPATA",dir:"AV. 15 DE AGOSTO N° 529",ref:"A ESPALDAS DEL COLEGIO CARLOS FERMIN FITZCARRALD / CRUCE CON JR. ICA",a:1},
  {l:"EL TRIUNFO",d:"MADRE DE DIOS",p:"TAMBOPATA",t:"LAS PIEDRAS",dir:"AV. INTEROCEANICA KM. 1",ref:"AL COSTADO DEL GRIFO VIRGEN NATIVIDAD",a:1},
  {l:"MAZUKO",d:"MADRE DE DIOS",p:"TAMBOPATA",t:"INAMBARI",dir:"AV. LOS PIONEROS",ref:"AL COSTADO DEL TERMINAL TERRESTRE DE MAZUKO / AL PIE DE LA CARRETERA AL RIO INAMBARI",a:1},
  {l:"TAMBOPATA AV CIRCUNVALACION",d:"MADRE DE DIOS",p:"TAMBOPATA",t:"TAMBOPATA",dir:"AV. CIRCUNVALACION MZ. C LT. 01",ref:"A DOS CDRAS. DE LA CARRETERA INTEROCEANICA SUR / CRUCE CON JR. LAS MERCEDES CABELLO",a:1},
  {l:"TAMBOPATA AV UCAYALI  CO",d:"MADRE DE DIOS",p:"TAMBOPATA",t:"TAMBOPATA",dir:"AV. UCAYALI N° 473 - TAMBOPATA - TAMBOPATA - MADRE DE DIOS",ref:"AL COSTADO DE MOTOS SSENDA. AL FRENTE DEL COLEGIO SANTA FE",a:1},
  {l:"ILO CO PAMPA INALAMBRICA",d:"MOQUEGUA",p:"ILO",t:"ILO",dir:"URB. CIUDAD DEL PESCADOR",ref:"A DOS CUADRAS DEL PODER JUDICIAL",a:1},
  {l:"ILO PACOCHA",d:"MOQUEGUA",p:"ILO",t:"PACOCHA",dir:"AGRUPACIÓN DE FAMILIAS PUEBLO NUEVO M.Z E2 LT. COM2A SECT.",ref:"AL COSTADO DEL BANCO BCP",a:1},
  {l:"ILO PUERTO",d:"MOQUEGUA",p:"ILO",t:"ILO",dir:"JR. CALLAO PROLONGACIÓN MZ. N",ref:"A MEDIA CDRA. DE LA COOPERATIVA CUAJONE",a:1},
  {l:"CALLE LIMA",d:"MOQUEGUA",p:"MARISCAL NIETO",t:"MOQUEGUA",dir:"CALLE LIMA 190 - MARISCAL NIETO - MOQUEGUA",ref:"A DOS CUADRAS DEL PARQUE LOS HÉROES/ALAMEDA",a:1},
  {l:"CHEN CHEN",d:"MOQUEGUA",p:"MARISCAL NIETO",t:"MOQUEGUA",dir:"MZ. C LT. 24 – ASOCIACIÓN CÉSAR VIZCARRA – CENTRO POBLADO",ref:"AL COSTADO DEL OVALO CHEN CHEN",a:1},
  {l:"QUEBRADA LAS LECHUZAS CO",d:"MOQUEGUA",p:"MARISCAL NIETO",t:"MOQUEGUA",dir:"SECTOR QUEBRADA LAS LECHUZAS MOQUEGUA CALLE N°1 MZ H LT. 0",ref:"QUEBRADA DE LECHUZAS",a:1},
  {l:"SAN ANTONIO",d:"MOQUEGUA",p:"MARISCAL NIETO",t:"MOQUEGUA",dir:"Av. Santa Fortunata Mz. N5 Lt. 10 Asoc. Villa Moquegua San",ref:"A una cuadra de la Casa de la Mujer",a:1},
  {l:"OXAPAMPA",d:"PASCO",p:"OXAPAMPA",t:"OXAPAMPA",dir:"MZ. 239 SUB LOTE H – 1 OXAPAMPA - OXAPAMPA - PASCO",ref:"ENTRE AV. ANGÉLICA FREY Y JR. LIMA",a:1},
  {l:"VILLA RICA",d:"PASCO",p:"OXAPAMPA",t:"VILLA RICA",dir:"AV. LEOPOLDO KRAUSSE N° 442 VILLA RICA - OXAPAMPA - PASCO",ref:"ENTRE EL JR. POZUZO Y JR. COOPERATIVA, AL COSTADO DE LA NOTARÍA GUERRA Y A 20 METROS DE",a:1},
  {l:"CERRO DE PASCO",d:"PASCO",p:"PASCO",t:"CHAUPIMARCA",dir:"JR. HUARICAPCHA S/N A.H. TUPAC AMARU CHAUPIMARCA",ref:"FRENTE AL NUEVO TERMINAL",a:1},
  {l:"HUAYLLAY",d:"PASCO",p:"PASCO",t:"HUAYLLAY",dir:"calle Lima S/N Barrio Arenales Huayllay Pasco - REFERENCIA",ref:"AL COSTADO DEL COLEGIO CESAR VALLEJO",a:1},
  {l:"AYABACA",d:"PIURA",p:"AYABACA",t:"AYABACA",dir:"CALLE BOLOGNESI N° 136",ref:"A 2 CUADRAS DE LA PLAZA DE ARMAS DE AYABACA",a:1},
  {l:"PAIMAS",d:"PIURA",p:"AYABACA",t:"PAIMAS",dir:"AV. SULLANA S/N",ref:"FRENTE AL COMPLEJO EDUCATIVO JUAN VELASCO ALVARADO",a:1},
  {l:"HUANCABAMBA",d:"PIURA",p:"HUANCABAMBA",t:"HUANCABAMBA",dir:"AV. RAMON CASTILLA 0351 HUANCABAMBA - PIURA",ref:"A 1 CUADRA DE LA CAPILLA RAMON CASTILLA",a:1},
  {l:"CHULUCANAS",d:"PIURA",p:"MORROPON",t:"CHULUCANAS",dir:"JR. HUANCAVELICA N° 548 REFERENCIA : AL LADO DEL TERMINAL",ref:"AL LADO DEL TERMINAL DE RONCO",a:1},
  {l:"MORROPON",d:"PIURA",p:"MORROPON",t:"MORROPON",dir:"JR. ADRIANZÉN N° 099",a:1},
  {l:"PAITA",d:"PIURA",p:"PAITA",t:"PAITA",dir:"MZ. H LT. 14 URB. SOL Y MAR - PAITA",ref:"AL COSTADO DE LA EMPRESA SAN MIGUEL",a:1},
  {l:"AAHH SANTA ROSA PIURA",d:"PIURA",p:"PIURA",t:"26 DE OCTUBRE",dir:"URB. SANTA ROSA MZ. D LT. 7",ref:"AV. RAUL MATA LA CRUZ CON CIRCUNVALACIÓN AL FRENTE DE REPUESTOS FRANK|",a:1},
  {l:"AEROPUERTO PIURA",d:"PIURA",p:"PIURA",t:"PIURA",dir:"Aeropuerto Internacional Guillermo Concha Ibérico"},
  {l:"AV RAUL MATA LA CRUZ- DOS GRIFOS",d:"PIURA",p:"PIURA",t:"PIURA",dir:"AV. RAÚL MATA LA CRUZ LT. 11 MZ. C URB. LOS JARDINES - COR",ref:"A UNA CDRA. DE LOS 2 GRIFOS EN TODA LA AV. RAÚL MATA LA CRUZ",a:1},
  {l:"AV TACNA",d:"PIURA",p:"PIURA",t:"CASTILLA",dir:"AV. TACNA 503 CASTILLA - PIURA",ref:"FRENTE A UGEL DE CASTILLA",a:1},
  {l:"AV. GRAU",d:"PIURA",p:"PIURA",t:"PIURA",dir:"Av. grau manzana N",ref:"Grau con marcavelica",a:1},
  {l:"AV. GULLMAN",d:"PIURA",p:"PIURA",t:"26 DE OCTUBRE",dir:"A.A.H.H. CONSUELO DE VELASCO 1 ETAPA SECTOR B MZ LT.18 26",ref:"CRUCE AV. CIRCUNVALACIÓN CON AV. GULLMAN AL COSTADO DE LA FERRETERIA LOS REYES",a:1},
  {l:"AV. LUIS EGUIGUREN",d:"PIURA",p:"PIURA",t:"PIURA",dir:"AV. MÁLAGA MZ. A LT.20 INT. 105 PIURA",ref:"A MEDIA CUADRA DE HONDA DEL PERU S.A. EN EL CRUCE DE AV. LUIS EGUIGUREN CON SULLANA NORTE",a:1},
  {l:"CALLE EMAÚS",d:"PIURA",p:"PIURA",t:"26 DE OCTUBRE",dir:"CALLE TRES N° 102",ref:"AL COSTADO DE SENATI",a:1},
  {l:"CATACAOS",d:"PIURA",p:"PIURA",t:"CATACAOS",dir:"AV. FRANCISCO BOLOGNESI MZ. 60 LT. 37 CATACAOS - PIURA - P",ref:"AL LADO DEL EX PRONEI",a:1},
  {l:"LA UNION",d:"PIURA",p:"PIURA",t:"LA UNION",dir:"AV. LIMA N° 590 REFERENCIA : frente a tiendas chancafe",ref:"frente a tiendas chancafe",a:1},
  {l:"LAS LOMAS",d:"PIURA",p:"PIURA",t:"LAS LOMAS",dir:"JR. MIGUEL GRAU MZ. H LT. 7",ref:"AL COSTADO DE CAJA HUANCAYO Y AL COSTADO DE COMISARIA LAS LOMAS",a:1},
  {l:"PARQUE INDUSTRIAL CO PIURA FUTURA",d:"PIURA",p:"PIURA",t:"26 DE OCTUBRE",dir:"URB. PARQUE INDUSTRIAL PIURA FUTURA MZ. G",ref:"AL FRENTE DEL GRIFO PETRO PERÚ",a:1},
  {l:"TACALA",d:"PIURA",p:"PIURA",t:"CASTILLA",dir:"CARR. PANAMERICANA A-2 AH. ALMIRANTE MIGUEL GRAU I ETAPA",ref:"AL COSTADO DE CERÁMICAS SAN LORENZO",a:1},
  {l:"TAMBO GRANDE",d:"PIURA",p:"PIURA",t:"TAMBO GRANDE",dir:"AA. HH. EL HUERTO MZ. E LT. 08 TAMBO GRANDE – PIURA - PIUR",ref:"ATRÁS DEL COLEGIO INA 54 AGROPECUARIO, A LA ALTURA DEL CAMPO CAMPESTRE RIVERA DEL RÍO",a:1},
  {l:"SECHURA",d:"PIURA",p:"SECHURA",t:"SECHURA",dir:"AV. BAYOVAR N° 311 REFERENCIA : AL COSTADO DE ANTENA 10 RA",ref:"AL COSTADO DE ANTENA 10 RADIO",a:1},
  {l:"BELLAVISTA SULLANA",d:"PIURA",p:"SULLANA",t:"BELLAVISTA",dir:"CALLE MOQUEGUA 381",ref:"REST. PARRILLADAS CHAVELOS",a:1},
  {l:"IGNACIO ESCUDERO",d:"PIURA",p:"SULLANA",t:"IGNACIO ESCUDERO",dir:"AV. PANAMERICANA CALLE 26 LOTE 3",ref:"FRENTE A LA INSTITUCIÓN EDUCATIVA IGNACIO ESCUDERO",a:1},
  {l:"SULLANA CO ZONA INDUSTRIAL",d:"PIURA",p:"SULLANA",t:"SULLANA",dir:"CTRA. SULLANA Nº S/N MZ. K",ref:"AL COSTADO DEL HOTEL COCO SUITE",a:1},
  {l:"SULLANA SANTA ROSA",d:"PIURA",p:"SULLANA",t:"SULLANA",dir:"Carretera Panamericana Norte Nº 790 SULLANA REFERENCIA : F",ref:"FRENTE AL COLEGIO CHIQUITITOS",a:1},
  {l:"EL ALTO",d:"PIURA",p:"TALARA",t:"EL ALTO",dir:"AV. BOLOGNESI O-37 CENTRO EL ALTO",ref:"A ESPALDAS DE LA MUNICIPALIDAD DE EL ALTO",a:1},
  {l:"LOS ORGANOS",d:"PIURA",p:"TALARA",t:"LOS ORGANOS",dir:"Av. Panamericana Norte P-29 - URB. Cercado zona URBANA",ref:"al frente de grifo de troncos o grifo San Pedro",a:1},
  {l:"MÁNCORA",d:"PIURA",p:"TALARA",t:"MANCORA",dir:"AV. GRAU NRO. 432 MÁNCORA - TALARA - PIURA",ref:"FRENTE AL PARADERO DE AUTOS DE LOS ÓRGANOS EN TODA LA PANAMERICANA NORTE",a:1},
  {l:"TALARA  CO ASOC CALIFORNIA",d:"PIURA",p:"TALARA",t:"PARINAS",dir:"ASOCIACIÓN CALIFORNIA C - 03 FRENTE A CARRETERA NEGRITOS",ref:"AL COSTADO DEL RESTAURANTE MI TORETE",a:1},
  {l:"TALARA ALTA 9 DE OCTUBRE",d:"PIURA",p:"TALARA",t:"PARINAS",dir:"MZ. N-10 AA.HH 9 DE OCTUBRE TALARA ALTA",ref:"A 1 CDRA. ANTES DE AMECFA",a:1},
  {l:"TALARA BAJA PARQUE 22",d:"PIURA",p:"TALARA",t:"PARINAS",dir:"PARQUE 22 – 03 LATERAL. TALARA BAJA",ref:"FRENTE A MINSA",a:1},
  {l:"AZANGARO",d:"PUNO",p:"AZANGARO",t:"AZANGARO",dir:"AV. PRÓCERES S/N",ref:"A DOS CDRAS. DEL PARQUE DE LA MADRE / A ORILLAS DE LA MISMA AV. PROCERES",a:1},
  {l:"DESAGUADERO",d:"PUNO",p:"CHUCUITO",t:"DESAGUADERO",dir:"AV. PANAMERICANA N° 1158 - 1160",ref:"AL COSTADO DEL GRIFO BARTOLOMÉ",a:1},
  {l:"ILAVE",d:"PUNO",p:"EL COLLAO",t:"ILAVE",dir:"JR. BOLOGNESI NRO. 866 BARRIO CRUZANI",ref:"A UNA CUADRA DEL COLISEO Y DEL CEMENTERIO DE ILAVE",a:1},
  {l:"AYAVIRI",d:"PUNO",p:"MELGAR",t:"AYAVIRI",dir:"JR. SANTA ROSA PROLONGACIÓN S/N MAGISTERIAL - PUNO - MELGA",ref:"A 50 METROS DEL ÓVALO, SALIDA A JULIACA",a:1},
  {l:"ALTO PUNO",d:"PUNO",p:"PUNO",t:"PUNO",dir:"URB. SAN PEDRO-ALTO PUNO",ref:"A TRES CDRAS. DE LA AV. QUE VA A JULIACA / A DOS CDRAS. DEL GRIFO BRONCO",a:1},
  {l:"AV  4 DE NOVIEMBRE CO",d:"PUNO",p:"PUNO",t:"PUNO",dir:"AV. 4 DE NOVIEMBRE N° 474-B Y 486-B BARRIO SANTA ROSA",ref:"A UNA CDRA. DE SUNAFIL",a:1},
  {l:"AV COSTANERA",d:"PUNO",p:"PUNO",t:"PUNO",dir:"AV. COSTANERA N° 211 CON JR. LOS INCAS - PUNO",a:1},
  {l:"SALCEDO",d:"PUNO",p:"PUNO",t:"PUNO",dir:"URB. AZIRUNI TEPRO I ETAPA MZ. 18 LT. 52 JR LOS ROSALES –",ref:"A UNA CDRA. DE LA AV. ESTUDIANTE / A DOS CDRAS. DE SENATI PUNO",a:1},
  {l:"AEROPUERTO JULIACA",d:"PUNO",p:"SAN ROMAN",t:"JULIACA",dir:"Aeropuerto Internacional Inca Manco Capac"},
  {l:"AV  INDEPENDENCIA",d:"PUNO",p:"SAN ROMAN",t:"JULIACA",dir:"AV. INDEPENDENCIA NRO. 1538 MZ. A1 LT. 04 URB. HORACIO ZEB",a:1},
  {l:"AV HEROES DEL PACIFICO CO",d:"PUNO",p:"SAN ROMAN",t:"JULIACA",dir:"AV. HÉROES DE LA GUERRA DEL PACIFICO KM 3.5",ref:"AL FRENTE DEL GRIFO LEON SERVICE",a:1},
  {l:"AV. HUANCANE CDRA. 9",d:"PUNO",p:"SAN ROMAN",t:"JULIACA",dir:"JR. SILLUSTANI N° 202",ref:"A 3 CDRAS. DEL HOSPITAL CARLOS MONGE MEDRANO",a:1},
  {l:"AV. LAMPA",d:"PUNO",p:"SAN ROMAN",t:"JULIACA",dir:"AV. LAMPA MZ. B2 LT. 3 URB. SANTA ADRIANA",ref:"A MEDIA CDRA. DE LA POSTA DE SALUD DE LA URB. SANTA ADRIANA",a:1},
  {l:"AV. MODESTO BORDA",d:"PUNO",p:"SAN ROMAN",t:"JULIACA",dir:"AV. MODESTO BORDA MZ. A LT. 04 URB. ARRABAL DON JULIO",ref:"DOS CDRAS. ANTES DEL GRIFO BLANCO / A DOS CDRAS. DEL SALON DE EVENTOS PARAISO AZUL",a:1},
  {l:"JR AGUSTIN GAMARRA",d:"PUNO",p:"SAN ROMAN",t:"JULIACA",dir:"JR. AGUSTIN GAMARRA MZ. R1 LT. 09 URB. HUANCANE",ref:"A UNA CDRA. DE LA AV. HUANCANE / CRUCE CON JR. ALBERTO CUENTAS ZABALA",a:1},
  {l:"JR. MAMA OCLLO",d:"PUNO",p:"SAN ROMAN",t:"JULIACA",dir:"Jr. Mama Ocllo 915 - B ( Cruce con Jr Azángaro )",a:1},
  {l:"LAS MERCEDES",d:"PUNO",p:"SAN ROMAN",t:"JULIACA",dir:"JR. PORVENIR N° 228 URB. LAS MERCEDES",ref:"A UNA CDRA. DE LA AV. CIRCUNVALACION OESTE - A UNA CDRA. DEL TERMINAL LAS MERCEDES",a:1},
  {l:"SAN MARTIN BELLAVISTA",d:"SAN MARTIN",p:"BELLAVISTA",t:"BELLAVISTA",dir:"AV. LIMA S/N C-4 MZ 71 – LOTE A – TERCER PISO",ref:"ESPALDAS DE FERRETERÍA EL IMAN",a:1},
  {l:"SAN JOSE DE SISA",d:"SAN MARTIN",p:"EL DORADO",t:"SAN JOSE DE SISA",dir:"JR. BOLOGNESI CDRA 6",ref:"ALTURA DE JR LAMAS Y JR ELADIO TAPULLIMA",a:1},
  {l:"SAPOSOA",d:"SAN MARTIN",p:"HUALLAGA",t:"SAPOSOA",dir:"AV. LORETO S/N - SAPOSOA - EL HUALLAGA - SAN MARTIN",ref:"EN EL HOSTAL EL GATO, A UNA CDRA. Y MEDIA DE LA PLAZA DE ARMAS"},
  {l:"LAMAS",d:"SAN MARTIN",p:"LAMAS",t:"LAMAS",dir:"JR. 16 DE OCTUBRE N°1137",ref:"A LA ESPALDA DEL GRIFO VARGAS TELLO",a:1},
  {l:"JUANJUI  CENTRO",d:"SAN MARTIN",p:"MARISCAL CACERES",t:"JUANJUI",dir:"JR. SARGENTO LOREZ N° 568",ref:"A UNA CDRA. DE DEL JR. HUALLAGA CDRA. 11 Y A UNA CDRA. DE IMPORTACIONES PATRICIA",a:1},
  {l:"JUANJUÍ FERNANDO BELAUNDE TERRY CO",d:"SAN MARTIN",p:"MARISCAL CACERES",t:"JUANJUI",dir:"CARRETERA FERNANDO TERRY KM. 1 S/N REFERENCIA: AL COSTADO",ref:"AL COSTADO DE PARADERO DE AUTOS HUALLAGA EXPRESS",a:1},
  {l:"MOYOBAMBA  CENTRO",d:"SAN MARTIN",p:"MOYOBAMBA",t:"MOYOBAMBA",dir:"JR. SERAFÍN FILOMENO N°279",ref:"A UNA CUADRA IMEDIA DEL CUMO (CENTRO CULTURAL DE MOYOBAMBA)",a:1},
  {l:"MOYOBAMBA  CO",d:"SAN MARTIN",p:"MOYOBAMBA",t:"MOYOBAMBA",dir:"JR. 20 de abril 2138 - REFERENCIA : Altura de la pampa del",ref:"Altura de la pampa del hambre",a:1},
  {l:"SORITOR",d:"SAN MARTIN",p:"MOYOBAMBA",t:"SORITOR",dir:"JR. MIGUEL GRAU CDRA 7 N°741 MZ.05 LTE.16B",ref:"A MEDIA CDRA. DE LA IGLESIA ASAMBLEAS DE DIOS",a:1},
  {l:"PICOTA",d:"SAN MARTIN",p:"PICOTA",t:"PICOTA",dir:"AV. FERNANDO BELAUNDE TERRY LOTE 2B PICOTA - PICOTA - SAN",a:1},
  {l:"NUEVA CAJAMARCA",d:"SAN MARTIN",p:"RIOJA",t:"NUEVA CAJAMARCA",dir:"AV. CAJAMARCA NORTE MZ. 51 LT. 15",ref:"AL COSTADO DE ESSALUD",a:1},
  {l:"PARDO MIGUEL NARANJOS",d:"SAN MARTIN",p:"RIOJA",t:"PARDO MIGUEL",dir:"JR. MIGUEL GRAU 101 MZ. 34 LT. 6",ref:"AV. MARGINAL CDRA 5",a:1},
  {l:"RIOJA",d:"SAN MARTIN",p:"RIOJA",t:"RIOJA",dir:"CTRA. FERNANDO BELAÚNDE TERRY N° 415",ref:"AL COSTADO DE LA CLÍNICA CHILCON HOPE",a:1},
  {l:"SEGUNDA JERUSALEN",d:"SAN MARTIN",p:"RIOJA",t:"ELIAS SOPLIN VARGAS",dir:"JR. LIMA MZ. 43 LT. 08",ref:"AL COSTADO DE TIENDA CHINGAY",a:1},
  {l:"AEROPUERTO TARAPOTO",d:"SAN MARTIN",p:"SAN MARTIN",t:"TARAPOTO",dir:"Aeropuerto Guillermo del Castillo Paredes"},
  {l:"JR LEONCIO PRADO",d:"SAN MARTIN",p:"SAN MARTIN",t:"TARAPOTO",dir:"JR. LEONCIO PRADO N° 1175",ref:"A UNA CUADRA DEL INSTITUTO MARÍA PARADO DE BELLIDO",a:1},
  {l:"JR. RAMÓN CASTILLA",d:"SAN MARTIN",p:"SAN MARTIN",t:"TARAPOTO",dir:"JR. RAMON CASTILLA N°1362 TARAPOTO - SAN MARTIN",ref:"A MEDIA CDRA. DE MANNUCCI MOTOR S.A",a:1},
  {l:"JR. TAHUANTINSUYO",d:"SAN MARTIN",p:"SAN MARTIN",t:"TARAPOTO",dir:"JR. TAHUANTINSUYO N° 158 - TARAPOTO - SAN MARTÍN",ref:"AL COSTADO DEL GRIFO SAN MARTÍN",a:1},
  {l:"TARAPOTO CO JR ALFONSO UGARTE",d:"SAN MARTIN",p:"SAN MARTIN",t:"TARAPOTO",dir:"JR. ALFONSO UGARTE N°2283 - TARAPOTO - SAN MARTIN - SAN MA",ref:"FRENTE A LA CANCHA SINTÉTICO EL GOLAZO",a:1},
  {l:"TARAPOTO JR. SARGENTO LOREZ",d:"SAN MARTIN",p:"SAN MARTIN",t:"MORALES",dir:"JR. SARGENTO LOREZ N° 264",ref:"A UNA CDRA. Y MEDIA DE LA PLAZA DE MORALES, FRENTE A VULCANO GAS",a:1},
  {l:"TARAPOTO LA BANDA DE SHILCAYO",d:"SAN MARTIN",p:"SAN MARTIN",t:"LA BANDA DE SHILCAYO",dir:"JR. PERÚ N°186",ref:"A 2 CDRS. DE LA PLAZA DE LA BANDA DE SHILCAYO",a:1},
  {l:"AV FERNANDO BELAUNDE",d:"SAN MARTIN",p:"TOCACHE",t:"TOCACHE",dir:"AV. FERNANDO BELAUNDE C-09 MZ H6 (21)",ref:"FRENTE AL MERCADILLO DE TOCACHE",a:1},
  {l:"JR  FREDY ALIAGA CO",d:"SAN MARTIN",p:"TOCACHE",t:"TOCACHE",dir:"JR. FREDY ALIAGA N°3046 -TOCACHE - TOCACHE - SAN MARTIN",ref:"AL COSTADO DEL RECREO CAMPESTRE ESTRAGOS",a:1},
  {l:"UCHIZA",d:"SAN MARTIN",p:"TOCACHE",t:"UCHIZA",dir:"AV. LEONCIO PRADO N°524 - UCHIZA - TOCACHE - SAN MARTIN",ref:"A MEDIA CDRA. DE LA PLAZA CENTRAL / FRENTE A COOPACT",a:1},
  {l:"AEROPUERTO TACNA",d:"TACNA",p:"TACNA",t:"TACNA",dir:"Aeropuerto Internacional Coronel Carlos Ciriani Santa Rosa"},
  {l:"AV  VIGIL",d:"TACNA",p:"TACNA",t:"TACNA",dir:"AV. VIGIL 1636",ref:"A UNA CDRA. DE LA PLAZA GRAU",a:1},
  {l:"AV EJERCITO",d:"TACNA",p:"TACNA",t:"TACNA",dir:"AV. LITORAL NRO. 306 – PARA CHICO (ANTERIOR AV. EJÉRCITO P",ref:"DENTRO DEL ESTABLECIMIENTO DEL GRIFO PRIMAX",a:1},
  {l:"AV. ARIAS ARAGUEZ",d:"TACNA",p:"TACNA",t:"TACNA",dir:"CALLE ARIAS ARAGUEZ N° 836 TACNA",ref:"A UNA CDRA. ANTES DE LLEGAR AL COLISEO PERÚ",a:1},
  {l:"AV. MUNICIPAL",d:"TACNA",p:"TACNA",t:"CORONEL GREGORIO ALBARRACIN LANCHIPA",dir:"ASOCIACIÓN LAS VILCAS MZ. E LT. 16",ref:"FRENTE AL MERCADO HÉROES DEL CENEPA",a:1},
  {l:"POCOLLAY",d:"TACNA",p:"TACNA",t:"TACNA",dir:"PUEBLO TRADICIONAL POCOLLAY MZ. T LOTE 01",ref:"A UNA CDRA. DEL CENTRO DE SALUD POCOLLAY",a:1},
  {l:"TACNA CIUDAD NUEVA",d:"TACNA",p:"TACNA",t:"CIUDAD NUEVA",dir:"CIUDAD NUEVA MZ 46 LT 12 COMITÉ 10 CIUDAD NUEVA - TACNA",ref:"A UNA CDRA. DE LA PLAZA JOSÉ OLAYA DE CIUDAD NUEVA",a:1},
  {l:"TACNA CO AV. JORGE BASADRE",d:"TACNA",p:"TACNA",t:"TACNA",dir:"Av. Jorge Basadre Grohmann Oeste n° 366 - tACNA",a:1},
  {l:"VILLA SAN FRANCISCO",d:"TACNA",p:"TACNA",t:"CORONEL GREGORIO ALBARRACIN LANCHIPA",dir:"ASOC. VILLA SAN FRANCISCO MZ. 94 LT. 22",ref:"CERCA A CAJA CUSCO",a:1},
  {l:"VIÑANIS",d:"TACNA",p:"TACNA",t:"CORONEL GREGORIO ALBARRACIN LANCHIPA",dir:"PROMUVI VIÑANI",ref:"A MEDIA CDRA. DEL ÓVALO LOS MOLLES",a:1},
  {l:"ZORRITOS",d:"TUMBES",p:"CONTRALMIRANTE VILLA",t:"ZORRITOS",dir:"AV. 28 DE JULIO N° 205 MZ. 14 LT. 04 LOS PINOS TUMBES",a:1},
  {l:"AEROPUERTO TUMBES",d:"TUMBES",p:"TUMBES",t:"TUMBES",dir:"Aeropuerto Internacional Pedro Canga Rodríguez"},
  {l:"CORRALES",d:"TUMBES",p:"TUMBES",t:"CORRALES",dir:"AV. HUÁSCAR Nº 311 INT. 01 CENTRO",ref:"A ESPALDAS DE LA PLAZA DE ARMAS",a:1},
  {l:"LA CRUZ  TUMBES",d:"TUMBES",p:"TUMBES",t:"LA CRUZ",dir:"JR. PIURA 105 CALETA LA CRUZ",ref:"FRENTE A CTR. PANAMERICANA NORTE Y AL FRENTE DE MOTOREPUESTOS Y MULTISERVICIOS LUJAN",a:1},
  {l:"PAMPA GRANDE TUMBES",d:"TUMBES",p:"TUMBES",t:"TUMBES",dir:"MZ. 0U LT. 00A AA.HH. PAMPA GRANDE",ref:"FRENTE A LA AV. UNIVERSITARIA, Y AL FRENTE A LA IGLESIA MORMONES Y AL LADO DE UN LAVADERO",a:1},
  {l:"TUMBES - AV ARICA",d:"TUMBES",p:"TUMBES",t:"TUMBES",dir:"Av. Arica N° 227 - Tumbes.",a:1},
  {l:"TUMBES CO - PANAMERICANA NORTE KM 2360",d:"TUMBES",p:"TUMBES",t:"TUMBES",dir:"AV. PANAMERICANA NORTE S/N VILLA PRIMAVERA - TUMBES. REF.",ref:"PASANDO SENATI FRENTE A AGRIPAC",a:1},
  {l:"TUMBES PUYANGO",d:"TUMBES",p:"TUMBES",t:"TUMBES",dir:"URB. ANDRÉS ARAUJO MORÁN MZ. 28-A LOTE 03 CALLE JACINTO SE",ref:"AL COSTADO DEL MERCADO PUYANGO",a:1},
  {l:"AGUAS VERDES",d:"TUMBES",p:"ZARUMILLA",t:"AGUAS VERDES",dir:"AV TUMBES S/N LOTE 09 MZ 17",ref:"A UNA CUADRA DEL PARQUE TOMAS ARIZOLA",a:1},
  {l:"ZARUMILLA",d:"TUMBES",p:"ZARUMILLA",t:"ZARUMILLA",dir:"JIRON INDEPENDENCIA 309 ZARUMILLA",ref:"ATRÁS DE LA PLAZA DE ARMAS Y FRENTE AL DORADO PASANDO 5 CASAS",a:1},
  {l:"AEROPUERTO PUCALLPA",d:"UCAYALI",p:"CORONEL PORTILLO",t:"PUCALLPA CALLERIA",dir:"Aeropuerto David Abensur Rengifo"},
  {l:"CALLERIA AV SAENZ PEÑA",d:"UCAYALI",p:"CORONEL PORTILLO",t:"PUCALLPA CALLERIA",dir:"AV. SAENZ PEÑA 229",ref:"A DOS CUADRAS DEL OVALO DE FEDERICO BASADRE Y SAENZ PEÑA",a:1},
  {l:"CALLERIA JR JOSE GALVEZ",d:"UCAYALI",p:"CORONEL PORTILLO",t:"PUCALLPA CALLERIA",dir:"Jr. Jose Galvez 147 calleria - CORONEL PORTILLO - Ucayali.",ref:"a media cuadra de la Av. Centenario",a:1},
  {l:"MANANTAY  AV AGUAYTIA",d:"UCAYALI",p:"CORONEL PORTILLO",t:"PUCALLPA MANANTAY",dir:"AV. AGUAYTIA MZ.",ref:"A MEDIA CDRA. DEL NUEVO MERCADO DE SAN FERNANDO",a:1},
  {l:"MANANTAY AV TUPAC AMARU",d:"UCAYALI",p:"CORONEL PORTILLO",t:"PUCALLPA MANANTAY",dir:"AV. TUPAC AMARU 2315 MANANTAY - CORONEL PORTILLO - UCAYALI",ref:"A MEDIA CDRA. DE LA POLLERIA EMANUEL",a:1},
  {l:"PUCALLPA CO FEDERICO BASADRE",d:"UCAYALI",p:"CORONEL PORTILLO",t:"PUCALLPA YARINACOCHA",dir:"CARRETERA FEDERICO BASADRE KM 6.800 YARINACOCHA - CORONEL",ref:"Entrada del Asentamiento Humano Alan Sisley",a:1},
  {l:"YARINACOCHA  AV UNIVERSITARIA",d:"UCAYALI",p:"CORONEL PORTILLO",t:"PUCALLPA YARINACOCHA",dir:"AV. UNIVERSITARIA MZA A LOTE 6",ref:"A MEDIA CDRA. DEL LOCAL ROKALPA",a:1},
  {l:"YARINACOCHA CENTRO",d:"UCAYALI",p:"CORONEL PORTILLO",t:"PUCALLPA YARINACOCHA",dir:"JR. TUPAC AMARU",ref:"A ESPALDA DE MAESTRANZA DE YARINACOCHA",a:1},
  {l:"AGUAYTÍA",d:"UCAYALI",p:"PADRE ABAD",t:"AGUAYTIA",dir:"U. VECINAL BARRIO UNIDO MZ. 1 LT. 2",ref:"AL COSTADO DEL TERMINAL TERRESTRE DE AGUAYTIA",a:1},
];

// Compat: el resto del código (y el Excel) trabaja con nombres sueltos.
export const AGENCIAS_SHALOM: string[] = AGENCIAS.map((a) => a.l);

const _n = (s: string) =>
  String(s ?? "").toUpperCase().normalize("NFD")
    .replace(/[̀-ͯ]/g, "").replace(/[^A-Z0-9]+/g, " ").trim();

// Las agencias que el texto puede estar nombrando. Compara contra el NOMBRE de
// la agencia, no contra su ciudad: "miraflores chiclayo" identifica una oficina,
// "chiclayo" no (ver agenciasDeCiudad).
export function candidatasAgencia(texto: string): string[] {
  const t = _n(texto);
  if (!t) return [];
  const exact = AGENCIAS_SHALOM.filter((a) => _n(a) === t);
  if (exact.length) return exact;
  return AGENCIAS_SHALOM.filter((a) => { const na = _n(a); return na && (t.includes(na) || na.includes(t)); });
}

// El cliente no escribe "CHICLAYO": escribe "la sede de Chiclayo nomás". Sin quitarle
// ese ruido, la ciudad no calzaba con ninguna y el motivo salía equivocado ("dijo una
// oficina que no está en la lista" cuando en realidad dijo su ciudad, donde hay varias).
const RUIDO_UBIC =
  /\b(LA|EL|LOS|LAS|UN|UNA|DE|DEL|EN|QUE|ESTA|QUEDA|POR|AHI|ALLA|MI|SU|NOMAS|SEDE|SEDES|OFICINA|OFICINAS|AGENCIA|AGENCIAS|SHALOM|SUCURSAL|LOCAL|TIENDA|PUNTO|CIUDAD)\b/g;
const _sinRuido = (s: string) => _n(s).replace(RUIDO_UBIC, " ").replace(/\s+/g, " ").trim();

// Las oficinas que hay en una ciudad. Lo que el cliente llama "mi ciudad" puede
// ser su distrito ("Pomalca"), su provincia ("Chiclayo") o su departamento
// ("Lambayeque"), así que se busca en los tres y se devuelve el corte MÁS FINO
// que dé resultados: si dice Chiclayo interesan las 4 del distrito, no las 14 de
// toda la provincia.
// Las oficinas de una ciudad, mirando SOLO los campos de lugar (distrito, provincia,
// departamento). Separado del público de abajo a propósito: aquel, si no encuentra
// nada, cae a "que la ciudad aparezca dentro del NOMBRE de la agencia", y ese último
// intento sirve para listarle opciones al cliente pero NO para decidir si lo que dijo
// era una ciudad o el nombre de una oficina.
function _deCiudadEstricto(ciudad: string): Agencia[] {
  const c = _n(ciudad);
  if (!c) return [];
  const limpio = _sinRuido(ciudad);
  if (limpio && limpio !== c) {
    const porLimpio = _deCiudadEstricto(limpio);
    if (porLimpio.length) return porLimpio;
  }
  const porDist = AGENCIAS.filter((a) => _n(a.t) === c);
  if (porDist.length) return porDist;
  const porProv = AGENCIAS.filter((a) => _n(a.p) === c);
  if (porProv.length) return porProv;
  return AGENCIAS.filter((a) => _n(a.d) === c);
}

export function agenciasDeCiudad(ciudad: string): Agencia[] {
  const estricto = _deCiudadEstricto(ciudad);
  if (estricto.length) return estricto;
  // Último intento: que la ciudad aparezca dentro del nombre de la agencia
  // ("HUANCAYO" → "HUANCAYO CO", "AEROPUERTO HUANCAYO").
  const c = _n(ciudad);
  return c ? AGENCIAS.filter((a) => _n(a.l).includes(c)) : [];
}

// ¿La oficina que dijo el cliente alcanza para despachar, o hay que confirmársela?
// Devuelve null si es segura, o el motivo para que un humano la coordine.
//
// Sigue valiendo la regla de siempre: esto CONFIRMA, no descarta. La lista es un
// volcado con fecha, no la verdad viva de Shalom.
export function sedeReconocida(sede: string, ciudad: string): string | null {
  const s = String(sede ?? "").trim();
  if (!s) {
    return String(ciudad ?? "").trim()
      ? "no dijo la oficina — confírmala con él antes de despachar"
      : "falta la sede/agencia de destino — confírmala";
  }
  // ⚠️ La coincidencia por nombre NO alcanza: hay agencias que se llaman igual o
  // parecido en departamentos distintos. Medido — una clienta de AREQUIPA pidió
  // "Shalom Arequipa Av Ejercito" y calzó con AV EJERCITO… que está en TACNA. El
  // pedido salió sin bandera y el paquete iba a cruzar medio país. Si sabemos su
  // ciudad, la candidata tiene que estar EN esa zona.
  const enSuZona = (a: Agencia) => {
    const c = _sinRuido(ciudad) || _n(ciudad);
    if (!c) return true;                       // sin ciudad no hay con qué filtrar
    return _n(a.t) === c || _n(a.p) === c || _n(a.d) === c || _n(a.l).includes(c);
  };
  const todas = candidatasAgencia(s);
  const deLaZona = AGENCIAS.filter((a) => todas.includes(a.l) && enSuZona(a));
  const cs = deLaZona.length ? deLaZona.map((a) => a.l) : [];
  if (todas.length && !deLaZona.length) {
    return `la oficina que dijo ("${s}") no es de su zona — confírmasela antes de despachar`;
  }
  if (cs.some((a) => _n(a) === _n(s))) return null;   // nombró una agencia tal cual
  // 🏙️ ¿Lo que dijo es una CIUDAD? Va ANTES del parecido de nombre, y por eso se mira
  // con `_deCiudadEstricto` (distrito/provincia/departamento, sin el "que la ciudad
  // aparezca dentro del nombre de la agencia", que es un último recurso para LISTARLE
  // opciones, no para decidir qué dijo).
  // Medido: dijo "Chiclayo" y el chat le mostró bien las CUATRO oficinas del distrito,
  // pero la bandera del pedido decía "hay 2 oficinas que calzan" — las dos que llevan
  // "Chiclayo" dentro del nombre (Aeropuerto y Miraflores). El operador leía 2 y el
  // cliente había visto 4: dos números distintos para la misma pregunta.
  const _ciudadDicha = _deCiudadEstricto(s);
  if (_ciudadDicha.length === 1) return null;
  if (_ciudadDicha.length > 1) {
    return `en ${_sinRuido(s) || s} hay ${_ciudadDicha.length} oficinas Shalom — confirma con él a cuál va`;
  }
  if (cs.length === 1) return null;                   // su texto apunta a una sola
  if (cs.length > 1) {
    return `hay ${cs.length} oficinas Shalom que calzan con "${s}" — confirma la exacta`;
  }
  // No nombró ninguna agencia. ¿Será que dijo su ciudad?
  const enCiudad = agenciasDeCiudad(s);
  if (enCiudad.length === 1) return null;             // esa ciudad tiene una sola
  if (enCiudad.length > 1) {
    return `en ${_sinRuido(s) || s} hay ${enCiudad.length} oficinas Shalom — confirma con él a cuál va`;
  }
  return "dijo una oficina que no está en la lista — confírmasela antes de despachar";
}

// Los OTROS distritos de su misma provincia donde también hay oficina. Cuando el
// cliente dice "soy de Chiclayo" se le muestran las 4 del distrito, que son las
// que le sirven… salvo que viva en Pimentel o Pomalca, que son provincia de
// Chiclayo y tienen la suya propia a la vuelta de la esquina. Con esto el bot
// puede ofrecérselas en vez de mandarlo al centro.
export function otrosDistritosConAgencia(ciudad: string): string[] {
  const c = _sinRuido(ciudad) || _n(ciudad);
  if (!c) return [];
  const enDist = AGENCIAS.filter((a) => _n(a.t) === c);
  if (!enDist.length) return [];   // no nombró un distrito → no hay "otros" que ofrecer
  const prov = _n(enDist[0].p);
  return [...new Set(
    AGENCIAS.filter((a) => _n(a.p) === prov && _n(a.t) !== c).map((a) => a.t),
  )];
}
